# The vilan toolchain — generated by scripts/brew-formula.sh in
# https://github.com/vilan-lang/vilan and pushed here by that repository's
# release workflow. Edit the script, never this file.
class Vilan < Formula
  desc "Language toolchain for vilan: the compiler and the language server"
  homepage "https://vilan-lang.github.io/vilan/"
  version "0.14.0"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/vilan-lang/vilan/releases/download/v0.14.0/vilan-aarch64-apple-darwin.tar.gz"
      sha256 "f4ccc413449dddd334549962719ba59f10e7091bc8b91f1d98bd2b8ef2a05343"
    end

    on_intel do
      url "https://github.com/vilan-lang/vilan/releases/download/v0.14.0/vilan-x86_64-apple-darwin.tar.gz"
      sha256 "491e6cc1cd945c4ec36d453d537a14c78d8d5a1a36d7175f57377f12bc275d23"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/vilan-lang/vilan/releases/download/v0.14.0/vilan-aarch64-unknown-linux-musl.tar.gz"
      sha256 "3e85a1f663efbcb610a88028aa0844e5ff3fbaf8010dfcf6d808c882d1639b68"
    end

    on_intel do
      url "https://github.com/vilan-lang/vilan/releases/download/v0.14.0/vilan-x86_64-unknown-linux-musl.tar.gz"
      sha256 "644d7df705d8b4ea92b9c912c6602d8ea94f553c34b21f5ee5571bc701f5f6d0"
    end
  end

  def install
    bin.install "vilan", "vilan-lsp"
    # Both licenses travel with the binaries they cover: the archive carries
    # them, and redistributing under either one means shipping its text.
    prefix.install "LICENSE-MIT", "LICENSE-APACHE"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/vilan --version")
  end
end
