// Adversarial expression/type fixtures for the handwritten frontend's regression
// corpus (`parse_expr_regression.rs` includes this file). Built from the grammar
// inventory: every operator at every adjacent-precedence boundary, the postfix /
// `?.` grouping cases, split shifts vs comparisons, unary stacking, `is` with its
// pattern subset, struct-literal vs condition ambiguity, i-string holes, and every
// type form (embedded in generic-argument position so `parse_type` is exercised).
//
// Through the H6 arc these were the S2 expression differential against the chumsky
// oracle (both frontends proven byte-identical). At the S5 cutover the oracle is
// deleted; the arrays live on as the parser's own regression corpus — the ACCEPT
// fixtures must parse cleanly (no errors, no panic), the DECLINER fixtures must
// still be rejected, and a curated precedence/grouping-critical subset is pinned
// with inline `Debug`-tree snapshots (the shapes a whole-file corpus sweep cannot
// isolate). Recovery shapes stay out of scope here (proposal §6a — S4 owns them).

/// Fixtures parsed in EXPRESSION position (`let __probe = <fixture>;`) — struct
/// literals are admitted as operands here.
const EXPRESSION_FIXTURES: &[&str] = &[
    // --- Literals ---------------------------------------------------------
    "0",
    "42",
    "1.5",
    "0.000",
    "0xFF",
    "0xDEADn",
    "1_000",
    "100u32",
    "3.14f",
    "true",
    "false",
    "null",
    "void",
    r#""hello""#,
    r#""""#,
    r#""with \"escaped\" quotes""#,
    r#""""a multiline""""#,
    // --- Identifiers ------------------------------------------------------
    "x",
    "foo_bar",
    "_x",
    "someReallyLongName",
    // --- i-strings (desugared token sequences) ----------------------------
    r#"i"hello""#,
    r#"i"""#,
    r#"i"a{x}b""#,
    r#"i"{x}""#,
    r#"i"{x + y}""#,
    r#"i"{a.b}""#,
    r#"i"{compute(a, b)}""#,
    r#"i"count is {count.get()}""#,
    r#"i"{x} and {y}""#,
    r#"i"prefix {a * b} suffix""#,
    r#"i"nested {f(g(x))}""#,
    r#"i"\{literal braces\}""#,
    // --- Static paths -----------------------------------------------------
    "A::B",
    "A::B::C",
    "Signal::Quit",
    "std::io::print",
    "List::new()",
    "List<str>::new()",
    "Map<K, V>::new()",
    "Result<T, E>::Ok(x)",
    "Option<i32>::None",
    "self::helper",
    // --- Parens and tuples ------------------------------------------------
    "(a)",
    "(a + b)",
    "((a))",
    "(((x)))",
    "(a, b)",
    "(a, b, c)",
    "(a + b, c * d)",
    "(f(x), g(y))",
    "(a, (b, c))",
    "((a, b), c)",
    // --- Lists and repeats ------------------------------------------------
    "[]",
    "[a]",
    "[a, b]",
    "[a, b, c]",
    "[a, b,]",
    "[1, 2, 3]",
    "[[1, 2], [3, 4]]",
    "[f(x), g(y)]",
    "[0; 5]",
    "[x; n]",
    "[a + b; 3]",
    "[default(); count]",
    // --- Struct initializers (expression mode) ----------------------------
    "Foo {}",
    "Foo { x = 1 }",
    "Foo { x = 1, y = 2 }",
    "Foo { x }",
    "Foo { x, y }",
    "Foo { x = 1, y = 2, }",
    "Point { x = a + b, y = c }",
    "Wrapper<T> { value = x }",
    "Outer { inner = Inner { v = 1 } }",
    // --- Calls ------------------------------------------------------------
    "f()",
    "f(a)",
    "f(a, b)",
    "f(a, b, c)",
    "f(a, b,)",
    "f<T>()",
    "f<T>(a)",
    "f<T, U>(a, b)",
    "f()()",
    "f(a)(b)",
    "f(g(h(x)))",
    "make<List<i32>>()",
    "default<Id>()",
    "compute(a + b, c * d)",
    // --- Member / index / postfix -----------------------------------------
    "a.b",
    "a.b.c",
    "a.b.c.d",
    "a.0",
    "a.1",
    "a.0.1",
    "a.method()",
    "a.method(x)",
    "a.method(x, y)",
    "a.method<T>(x)",
    "a.b.method()",
    "a.method().field",
    "a.read()(x)",
    "self.hook.read()(a)",
    "a[0]",
    "a[i]",
    "a[i][j]",
    "a[i + 1]",
    "list[f(x)]",
    "m[k].field",
    "handlers[0](x)",
    "a.b[0].c",
    "grid[i][j].value",
    // --- Try-assert and lift ----------------------------------------------
    "x!",
    "f()!",
    "a.b!",
    "a.method()!",
    "a?",
    "f()?",
    "a?.b",
    "a?.b.c",
    "a?.b?.c",
    "a?.method()",
    "a?.method().field",
    "a?.b[0]",
    "a?.b!",
    "a?.b?",
    "a.b?.c.d",
    "a?.b(x)?.c",
    "(a?)",
    "(a? + b?)",
    "(x?.y + z)",
    "a?.b?.c?.d",
    // --- Unary stacking ---------------------------------------------------
    "!x",
    "!!x",
    "!!!b",
    "-x",
    "- -x",
    "-a.b",
    "!a.b",
    "!f()",
    "await x",
    "await f()",
    "await a?.b",
    "async x",
    "async f()",
    "async { }",
    "async { f() }",
    "&x",
    "&mut x",
    "*x",
    "&*x",
    "*&x",
    "&mut a.b",
    "&list[0]",
    "!a == b",
    "-a + b",
    "a + -b",
    // --- Product / sum boundary -------------------------------------------
    "a * b",
    "a / b",
    "a % b",
    "a + b",
    "a - b",
    "a + b * c",
    "a * b + c",
    "(a + b) * c",
    "a - b - c",
    "a / b / c",
    "a * b / c % d",
    "a + b - c + d",
    // --- Shift vs comparison ----------------------------------------------
    "a << b",
    "a >> b",
    "1 << 8",
    "a << b << c",
    "a << b + c",
    "a + b << c",
    "a >> b & c",
    "a & b << c",
    "flags << 2 | mask",
    // --- Comparison -------------------------------------------------------
    "a == b",
    "a != b",
    "a < b",
    "a <= b",
    "a > b",
    "a >= b",
    "a < b < c",
    "a == b == c",
    "a < b == c",
    "a + b == c",
    "a == b + c",
    "a << b == c",
    // --- Bitwise ----------------------------------------------------------
    "a & b",
    "a ^ b",
    "a | b",
    "a & b | c",
    "a | b & c",
    "a & b ^ c",
    "a ^ b | c",
    "a & b == c",
    "a & b ^ c | d",
    // --- Logical ----------------------------------------------------------
    "a && b",
    "a || b",
    "a && b && c",
    "a || b || c",
    "a && b || c",
    "a || b && c",
    "a == b && c != d",
    "a && b == c",
    "!a && !b",
    "a || b || c && d",
    // --- is patterns ------------------------------------------------------
    "x is None",
    "x is Some(let y)",
    "x is Ok(let v)",
    "outcome is Ok(let _opened)",
    "x is Enum::Variant",
    "x is Signal::Quit",
    "x is _",
    "x is 42",
    r#"x is "quit""#,
    "x is let y",
    "x is mut y",
    "x is (let a, let b)",
    "x is Point(let a, let b)",
    "x is Some(let y) && ready",
    "ready && x is None",
    "a is None || b is None",
    "x is Wrapper(Inner(let v))",
    // --- const ------------------------------------------------------------
    "const 5",
    "const a + b",
    "const f(x)",
    "const [1, 2, 3]",
    // --- Closures ---------------------------------------------------------
    "|x| x",
    "|x| x + 1",
    "|| 0",
    "|| f()",
    "|x, y| x + y",
    "|x: i32| x",
    "|x|: i32 x",
    "|x: i32|: i32 x + 1",
    "|(a, b)| a",
    "|[a, b]| a",
    "|x| |y| x + y",
    "map(|x| x * 2)",
    "items.map(|x| x * 2)",
    "reduce(|a, b| a + b, 0)",
    "|_| void",
    // --- Blocks as expressions --------------------------------------------
    "{ 0 }",
    "{ }",
    "{ f() }",
    "{ let x = 1; x }",
    "{ f(); g() }",
    "{ a; b; c }",
    "{ let x = 1; let y = 2; x + y }",
    // --- if / match / for as expressions ----------------------------------
    "if a { 1 } else { 2 }",
    "if a { 1 }",
    "if a { 1 } else if b { 2 } else { 3 }",
    "if a && b { c } else { d }",
    "if x is None { 0 } else { 1 }",
    "match x { }",
    "match x { let y => y }",
    "match x { Some(let a) => a, None => 0 }",
    r#"match x { 1 => "one", 2 => "two", _ => "other" }"#,
    "match x { let a if a > 0 => a, _ => 0 }",
    r#"match x { "a", "b" => 1, _ => 0 }"#,
    "for x in xs { f(x) }",
    "for a { b }",
    "for { jump break }",
    // --- jump / return / assignment as expressions ------------------------
    "jump break",
    "jump continue",
    "ret",
    "ret x",
    "ret a + b",
    "x = 5",
    "x += 1",
    "x -= 1",
    "x *= 2",
    "x /= 2",
    "x %= 2",
    "a.b = c",
    "list[i] = v",
    "*p = 5",
    "a.b.c = d",
    "*node.slot() = 10",
    // --- Types (embedded in generic-argument position) --------------------
    "g<i32>()",
    "g<str>()",
    "g<List<T>>()",
    "g<Map<K, V>>()",
    "g<&T>()",
    "g<&mut T>()",
    "g<[i32; 4]>()",
    "g<[[i32; 2]; 3]>()",
    "g<|A| B>()",
    "g<|| T>()",
    "g<|x: i32| bool>()",
    "g<async || T>()",
    "g<sync || T>()",
    "g<(A, B)>()",
    "g<(A)>()",
    "g<()>()",
    "g<(A, B, C)>()",
    "g<(U in T: F<U>)>()",
    "g<Foo context bar>()",
    "g<(|| T) context turn_scope>()",
    "g<(sync || T) context owner_scope>()",
    "g<|Nursery| T>()",
    "g<List<Option<T>>>()",
    "g<&List<i32>>()",
    "g<sync>()",
    // --- Deeply nested / mixed real-world ---------------------------------
    "count.get() + 1",
    "items.map(|x| x * 2).filter(|x| x > 0)",
    "self.value",
    "Foo { x = Bar { y = 1 } }",
    "f(|x| x + 1, 2)",
    "a.b(c.d(e))",
    "(a + b) * (c - d)",
    "matrix[i][j] * scalar + offset",
    "obj.field.method(arg).result",
    "cond && (a || b) && c",
    "list.push(compute(x, y))",
    "!ready || done && !failed",
    "a?.b.c?.d.e",
    // --- Trailing-member recovery (the LSP-critical mid-edit shapes) -------
    // The chumsky `.member`/`?.member` grammar recovers a missing member to an
    // `Error` node SILENTLY (0 parse errors, via `.or_not()`), so these parse
    // CLEAN — the receiver still types, which member completion relies on.
    "a.",
    "a?.",
    "a.b.",
    "self.hook.",
    // --- Real expressions harvested from the corpus / std -----------------
    "(10, \"hi\")",
    "((1, 2), 3)",
    "[ [ 1 ], [ 10, 20, 30 ] ]",
    "(1, (2, \"z\"))",
    "(a << 12) | (b << 6) | c",
    "(a << 18) | (b << 12) | (c << 6) | d",
    "28u32 - (4u32 * u32_of_nibble(nibble))",
    "2f.pow(0f - 52f)",
    "a.sub(|value| print(i\"a -> {value}\"))",
    "async self.settle(value, mine)",
    "async Promise::all(promises)",
    "BinaryReader::new(bytes)",
    "arg(request, 0)",
    "a.take()",
    "self.observed",
    "Bytes::alloc(0)",
    // --- Elements (element-syntax S2) --------------------------------------
    "<div/>",
    "<div />",
    "<div></div>",
    "<div class(\"x\")/>",
    "<input type(\"checkbox\") disabled/>",
    "<div aria-label(\"Copy command\")/>",
    "<my-widget/>",
    "<button on:click(add)>\"Add\"</button>",
    "<button on:click(|| go())/>",
    "<button on:click(|e| e.prevent_default())/>",
    "<div .styled(card) .show(f)/>",
    "<ul .bind_each(items, |t| t.id, |t| row(t))/>",
    "<p>\"text\"</p>",
    "<p>{value}</p>",
    "<p>i\"a {b}\"</p>",
    "<div><span/></div>",
    "<div/>.show(f)",
    "<p>\"a\" <b/> {c}</p>",
    "x < <div/>",            // a comparison whose right operand is an element
    "<div hidden.show(f)/>", // bare attr, then a chain link, no space (positional)
];

/// Fixtures parsed in CONDITION position (`if <fixture> { }`) — struct literals are
/// NOT admitted as operands (§H.1), so a bare name is an accessor and a following
/// `{` is the block.
const CONDITION_FIXTURES: &[&str] = &[
    "Foo",
    "x",
    "x.y",
    "ready",
    "!done",
    "a && b",
    "a || b",
    "a == b",
    "a != b",
    "a < b",
    "a <= b",
    "count > 10",
    "x is None",
    "x is Some(let y)",
    "x is Ok(let v) && ready",
    "f(x)",
    "list.len() > 0",
    "x.is_empty()",
    "count > 10 && ready",
    "a && b || c",
    "obj.field == expected",
    "!a && !b",
    "a is None || b is None",
    "self.done",
    "n % 2 == 0",
    // Parenthesised struct literals ARE allowed in a condition (parens reset to a
    // full expression) — the escape hatch §H.1 documents.
    "(Foo { x = 1 })",
    "(Config { verbose = true }).verbose",
    "flag & mask == 0",
    "a << 2 > b",
    "items.contains(x)",
];

/// WHOLE-FILE fixtures: item-free programs (statement sequences) that both
/// frontends parse end-to-end and unwrapped. No corpus file is item-free (every one
/// has a `fun`/`struct`/… item — the S3 seam), so these are the only source of
/// genuine whole-file `parse_program` coverage in S2: the `;`-terminated vs
/// block-bearing statement forms, the trailing-value rule, and statement
/// sequencing. Each is compared as a whole `NodeList`, span-inclusive.
const WHOLE_FILE_FIXTURES: &[&str] = &[
    "let x = 5;",
    "let x = 5;\nlet y = 10;\nx + y;",
    "x = 1;\ny = 2;",
    "f();\ng();\nh();",
    "if ready { start(); }",
    "if a { x } else { y }",
    "for item in items { consume(item); }",
    "for { jump break; }",
    "match sig { Quit => 0, Run(let n) => n }",
    "let total = items.map(|x| x * 2);",
    "let p = Point { x = 1, y = 2 };",
    "let r = a?.b?.c;",
    "let flags = (a << 2) | mask;",
    "let config = { let base = 10; base * 2 };\nprocess(config);",
    "let x = if cond { 1 } else { 2 };\nret x;",
    "if a { b } c;",
    "let n = compute(x, y);\nif n > 0 { report(n); } else { skip(); }\nn;",
];

/// Fixtures the chumsky oracle DECLINES (parse error / recovery) within the S2
/// subset — a guard that the handwritten parser is never MORE permissive than the
/// oracle (accepting something the grammar rejects). Each must decline through BOTH
/// frontends when wrapped as `let __probe = <fixture>;`.
const DECLINER_FIXTURES: &[&str] = &[
    "(a, b,)",   // the tuple atom has no `allow_trailing` (unlike a list)
    "(a,)",      // one element + trailing comma is neither tuple nor group
    "a < < b",   // a non-adjacent `< <` is not a shift (and not a valid comparison)
    "x is",      // `is` with no pattern
    "|x|",       // a closure with no body
    "f(a b)",    // a missing argument comma
    "[a; b; c]", // a repeat is `expr ; expr`, not two `;`
    "a::",       // a `::` with no member
    "match x {", // an unclosed match
    "(",         // an unclosed paren
    // --- Elements (element-syntax S2) --------------------------------------
    "<div>",             // an unclosed element
    "<div></span>",      // a mismatched closing tag
    "<h2>Todos</h2>",    // bare text children are quoted strings
    "<div name(a, b)/>", // an attribute takes one value
    "<div>< /div>",      // a non-adjacent `</` is not a close marker
];
