//! Every attribute name the HTML and SVG specifications define, by element
//! — the vocabulary vilan-ide's element-head completion offers at `<tag |>`
//! (tracker E69).
//!
//! GENERATED FILE -- do not hand-edit. The dataset is `html-attributes.tsv`
//! beside this file, vendored from the WHATWG HTML attribute index and the
//! SVG 2 attribute index by `scripts/regen-html-attributes.py --fetch`; this
//! file is what that script's DEFAULT mode makes of it. `html_attributes_sync`
//! beside it is the GATE: a second, independent implementation of the same
//! TSV -> table arrow, in Rust, which re-renders and diffs this file byte for
//! byte. It is OFFLINE, so no gate ever reaches the network and refreshing the
//! extract stays a deliberate commit.
//!
//! Rewrite after refreshing the dataset with
//! `VILAN_REGENERATE_HTML_ATTRIBUTES=1 cargo test -p vilan-ide html_attributes`,
//! or `python3 scripts/regen-html-attributes.py` — the two must agree, and the
//! gate is what says so.
//!
//! # What this table is NOT
//!
//! It is not a source of truth about vilan. The element desugar stays
//! NAME-BLIND (element-syntax.md §2, §9 item 3): `name(x)` lowers to
//! `.attr("name", x)` whatever `name` is, nothing here is consulted by the
//! parser, the desugar, the analyzer or the formatter, and a `data-*` name
//! absent from it costs one completion entry and nothing else. That is the
//! disanalogy E67's refusal turned on — "a second source of truth with
//! nothing to gate it" — and the generator plus the gate are that gate.

/// The global attributes: every element takes them (the HTML attribute
/// index's `HTML elements` rows).
pub const GLOBAL_ATTRIBUTES: &[&str] = &[
    "accesskey",
    "autocapitalize",
    "autocorrect",
    "autofocus",
    "class",
    "contenteditable",
    "dir",
    "draggable",
    "enterkeyhint",
    "headingoffset",
    "headingreset",
    "hidden",
    "id",
    "inert",
    "inputmode",
    "is",
    "itemid",
    "itemprop",
    "itemref",
    "itemscope",
    "itemtype",
    "lang",
    "nonce",
    "popover",
    "slot",
    "spellcheck",
    "style",
    "tabindex",
    "title",
    "translate",
    "writingsuggestions",
];

/// The SVG-wide vocabulary — the attribute index's section G.2
/// presentation attributes — offered on every [`SVG_ELEMENTS`] tag.
pub const SVG_GLOBAL_ATTRIBUTES: &[&str] = &[
    "alignment-baseline",
    "baseline-shift",
    "clip",
    "clip-path",
    "clip-rule",
    "color",
    "color-interpolation",
    "color-interpolation-filters",
    "color-rendering",
    "cursor",
    "direction",
    "display",
    "dominant-baseline",
    "fill",
    "fill-opacity",
    "fill-rule",
    "filter",
    "flood-color",
    "flood-opacity",
    "font-family",
    "font-size",
    "font-size-adjust",
    "font-stretch",
    "font-style",
    "font-variant",
    "font-weight",
    "glyph-orientation-horizontal",
    "glyph-orientation-vertical",
    "image-rendering",
    "letter-spacing",
    "lighting-color",
    "marker-end",
    "marker-mid",
    "marker-start",
    "mask",
    "opacity",
    "overflow",
    "paint-order",
    "pointer-events",
    "shape-rendering",
    "stop-color",
    "stop-opacity",
    "stroke",
    "stroke-dasharray",
    "stroke-dashoffset",
    "stroke-linecap",
    "stroke-linejoin",
    "stroke-miterlimit",
    "stroke-opacity",
    "stroke-width",
    "text-anchor",
    "text-decoration",
    "text-rendering",
    "transform",
    "unicode-bidi",
    "vector-effect",
    "visibility",
    "word-spacing",
    "writing-mode",
];

/// The `GlobalEventHandlers` event names with `on` stripped: vilan spells
/// the content attribute `onclick` as `on:click(…)`, so the table holds
/// what follows the colon. The `body`/`Window` handlers are a different
/// mixin and are not here.
pub const EVENTS: &[&str] = &[
    "auxclick",
    "beforeinput",
    "beforematch",
    "beforetoggle",
    "blur",
    "cancel",
    "canplay",
    "canplaythrough",
    "change",
    "click",
    "close",
    "command",
    "contextlost",
    "contextmenu",
    "contextrestored",
    "copy",
    "cuechange",
    "cut",
    "dblclick",
    "drag",
    "dragend",
    "dragenter",
    "dragleave",
    "dragover",
    "dragstart",
    "drop",
    "durationchange",
    "emptied",
    "ended",
    "error",
    "focus",
    "formdata",
    "input",
    "invalid",
    "keydown",
    "keypress",
    "keyup",
    "load",
    "loadeddata",
    "loadedmetadata",
    "loadstart",
    "mousedown",
    "mouseenter",
    "mouseleave",
    "mousemove",
    "mouseout",
    "mouseover",
    "mouseup",
    "paste",
    "pause",
    "play",
    "playing",
    "progress",
    "ratechange",
    "reset",
    "resize",
    "scroll",
    "scrollend",
    "securitypolicyviolation",
    "seeked",
    "seeking",
    "select",
    "slotchange",
    "stalled",
    "submit",
    "suspend",
    "timeupdate",
    "toggle",
    "volumechange",
    "waiting",
    "wheel",
];

/// The SVG-shaped tags: every element the SVG index names that the HTML
/// index does not, plus the SVG root. These take
/// [`SVG_GLOBAL_ATTRIBUTES`] on top of their own.
pub const SVG_ELEMENTS: &[&str] = &[
    "animate",
    "animateMotion",
    "animateTransform",
    "circle",
    "clipPath",
    "defs",
    "desc",
    "discard",
    "ellipse",
    "feBlend",
    "feColorMatrix",
    "feComponentTransfer",
    "feComposite",
    "feConvolveMatrix",
    "feDiffuseLighting",
    "feDisplacementMap",
    "feDistantLight",
    "feDropShadow",
    "feFlood",
    "feFuncA",
    "feFuncB",
    "feFuncG",
    "feFuncR",
    "feGaussianBlur",
    "feImage",
    "feMerge",
    "feMergeNode",
    "feMorphology",
    "feOffset",
    "fePointLight",
    "feSpecularLighting",
    "feSpotLight",
    "feTile",
    "feTurbulence",
    "filter",
    "foreignObject",
    "g",
    "image",
    "line",
    "linearGradient",
    "marker",
    "mask",
    "metadata",
    "mpath",
    "path",
    "pattern",
    "polygon",
    "polyline",
    "radialGradient",
    "rect",
    "set",
    "stop",
    "svg",
    "switch",
    "symbol",
    "text",
    "textPath",
    "tspan",
    "unknown",
    "use",
    "view",
];

/// Each tag's OWN attributes as `(tag, attribute)` pairs, ascending — the
/// globals above are not repeated, so a tag absent from this table takes
/// only the globals. Sorted, so a lookup is a binary search and a diff of
/// this file reads as a set difference; flat rather than nested so that
/// every line is short enough for `cargo fmt` to leave it exactly where the
/// generator put it (the gate compares the file BYTE for byte).
pub const ELEMENT_ATTRIBUTES: &[(&str, &str)] = &[
    ("a", "download"),
    ("a", "href"),
    ("a", "hreflang"),
    ("a", "ping"),
    ("a", "referrerpolicy"),
    ("a", "rel"),
    ("a", "target"),
    ("a", "type"),
    ("animate", "accumulate"),
    ("animate", "additive"),
    ("animate", "attributeName"),
    ("animate", "begin"),
    ("animate", "by"),
    ("animate", "calcMode"),
    ("animate", "dur"),
    ("animate", "end"),
    ("animate", "from"),
    ("animate", "href"),
    ("animate", "keySplines"),
    ("animate", "keyTimes"),
    ("animate", "max"),
    ("animate", "min"),
    ("animate", "repeatCount"),
    ("animate", "repeatDur"),
    ("animate", "requiredExtensions"),
    ("animate", "restart"),
    ("animate", "systemLanguage"),
    ("animate", "to"),
    ("animate", "values"),
    ("animateMotion", "accumulate"),
    ("animateMotion", "additive"),
    ("animateMotion", "begin"),
    ("animateMotion", "by"),
    ("animateMotion", "calcMode"),
    ("animateMotion", "dur"),
    ("animateMotion", "end"),
    ("animateMotion", "from"),
    ("animateMotion", "href"),
    ("animateMotion", "keyPoints"),
    ("animateMotion", "keySplines"),
    ("animateMotion", "keyTimes"),
    ("animateMotion", "max"),
    ("animateMotion", "min"),
    ("animateMotion", "origin"),
    ("animateMotion", "path"),
    ("animateMotion", "repeatCount"),
    ("animateMotion", "repeatDur"),
    ("animateMotion", "requiredExtensions"),
    ("animateMotion", "restart"),
    ("animateMotion", "rotate"),
    ("animateMotion", "systemLanguage"),
    ("animateMotion", "to"),
    ("animateMotion", "values"),
    ("animateTransform", "accumulate"),
    ("animateTransform", "additive"),
    ("animateTransform", "attributeName"),
    ("animateTransform", "begin"),
    ("animateTransform", "by"),
    ("animateTransform", "calcMode"),
    ("animateTransform", "dur"),
    ("animateTransform", "end"),
    ("animateTransform", "from"),
    ("animateTransform", "href"),
    ("animateTransform", "keySplines"),
    ("animateTransform", "keyTimes"),
    ("animateTransform", "max"),
    ("animateTransform", "min"),
    ("animateTransform", "repeatCount"),
    ("animateTransform", "repeatDur"),
    ("animateTransform", "requiredExtensions"),
    ("animateTransform", "restart"),
    ("animateTransform", "systemLanguage"),
    ("animateTransform", "to"),
    ("animateTransform", "type"),
    ("animateTransform", "values"),
    ("area", "alt"),
    ("area", "coords"),
    ("area", "download"),
    ("area", "href"),
    ("area", "ping"),
    ("area", "referrerpolicy"),
    ("area", "rel"),
    ("area", "shape"),
    ("area", "target"),
    ("audio", "autoplay"),
    ("audio", "controls"),
    ("audio", "crossorigin"),
    ("audio", "loading"),
    ("audio", "loop"),
    ("audio", "muted"),
    ("audio", "preload"),
    ("audio", "src"),
    ("base", "href"),
    ("base", "target"),
    ("blockquote", "cite"),
    ("button", "command"),
    ("button", "commandfor"),
    ("button", "disabled"),
    ("button", "form"),
    ("button", "formaction"),
    ("button", "formenctype"),
    ("button", "formmethod"),
    ("button", "formnovalidate"),
    ("button", "formtarget"),
    ("button", "name"),
    ("button", "popovertarget"),
    ("button", "popovertargetaction"),
    ("button", "type"),
    ("button", "value"),
    ("canvas", "height"),
    ("canvas", "width"),
    ("circle", "aria-activedescendant"),
    ("circle", "aria-atomic"),
    ("circle", "aria-autocomplete"),
    ("circle", "aria-busy"),
    ("circle", "aria-checked"),
    ("circle", "aria-colcount"),
    ("circle", "aria-colindex"),
    ("circle", "aria-colspan"),
    ("circle", "aria-controls"),
    ("circle", "aria-current"),
    ("circle", "aria-describedby"),
    ("circle", "aria-details"),
    ("circle", "aria-disabled"),
    ("circle", "aria-dropeffect"),
    ("circle", "aria-errormessage"),
    ("circle", "aria-expanded"),
    ("circle", "aria-flowto"),
    ("circle", "aria-grabbed"),
    ("circle", "aria-haspopup"),
    ("circle", "aria-hidden"),
    ("circle", "aria-invalid"),
    ("circle", "aria-keyshortcuts"),
    ("circle", "aria-label"),
    ("circle", "aria-labelledby"),
    ("circle", "aria-level"),
    ("circle", "aria-live"),
    ("circle", "aria-modal"),
    ("circle", "aria-multiline"),
    ("circle", "aria-multiselectable"),
    ("circle", "aria-orientation"),
    ("circle", "aria-owns"),
    ("circle", "aria-placeholder"),
    ("circle", "aria-posinset"),
    ("circle", "aria-pressed"),
    ("circle", "aria-readonly"),
    ("circle", "aria-relevant"),
    ("circle", "aria-required"),
    ("circle", "aria-roledescription"),
    ("circle", "aria-rowcount"),
    ("circle", "aria-rowindex"),
    ("circle", "aria-rowspan"),
    ("circle", "aria-selected"),
    ("circle", "aria-setsize"),
    ("circle", "aria-sort"),
    ("circle", "aria-valuemax"),
    ("circle", "aria-valuemin"),
    ("circle", "aria-valuenow"),
    ("circle", "aria-valuetext"),
    ("circle", "pathLength"),
    ("circle", "requiredExtensions"),
    ("circle", "role"),
    ("circle", "systemLanguage"),
    ("clipPath", "clipPathUnits"),
    ("clipPath", "requiredExtensions"),
    ("clipPath", "systemLanguage"),
    ("col", "span"),
    ("colgroup", "span"),
    ("data", "value"),
    ("del", "cite"),
    ("del", "datetime"),
    ("details", "name"),
    ("details", "open"),
    ("dialog", "closedby"),
    ("dialog", "open"),
    ("discard", "aria-activedescendant"),
    ("discard", "aria-atomic"),
    ("discard", "aria-autocomplete"),
    ("discard", "aria-busy"),
    ("discard", "aria-checked"),
    ("discard", "aria-colcount"),
    ("discard", "aria-colindex"),
    ("discard", "aria-colspan"),
    ("discard", "aria-controls"),
    ("discard", "aria-current"),
    ("discard", "aria-describedby"),
    ("discard", "aria-details"),
    ("discard", "aria-disabled"),
    ("discard", "aria-dropeffect"),
    ("discard", "aria-errormessage"),
    ("discard", "aria-expanded"),
    ("discard", "aria-flowto"),
    ("discard", "aria-grabbed"),
    ("discard", "aria-haspopup"),
    ("discard", "aria-hidden"),
    ("discard", "aria-invalid"),
    ("discard", "aria-keyshortcuts"),
    ("discard", "aria-label"),
    ("discard", "aria-labelledby"),
    ("discard", "aria-level"),
    ("discard", "aria-live"),
    ("discard", "aria-modal"),
    ("discard", "aria-multiline"),
    ("discard", "aria-multiselectable"),
    ("discard", "aria-orientation"),
    ("discard", "aria-owns"),
    ("discard", "aria-placeholder"),
    ("discard", "aria-posinset"),
    ("discard", "aria-pressed"),
    ("discard", "aria-readonly"),
    ("discard", "aria-relevant"),
    ("discard", "aria-required"),
    ("discard", "aria-roledescription"),
    ("discard", "aria-rowcount"),
    ("discard", "aria-rowindex"),
    ("discard", "aria-rowspan"),
    ("discard", "aria-selected"),
    ("discard", "aria-setsize"),
    ("discard", "aria-sort"),
    ("discard", "aria-valuemax"),
    ("discard", "aria-valuemin"),
    ("discard", "aria-valuenow"),
    ("discard", "aria-valuetext"),
    ("discard", "begin"),
    ("discard", "href"),
    ("discard", "requiredExtensions"),
    ("discard", "role"),
    ("discard", "systemLanguage"),
    ("ellipse", "aria-activedescendant"),
    ("ellipse", "aria-atomic"),
    ("ellipse", "aria-autocomplete"),
    ("ellipse", "aria-busy"),
    ("ellipse", "aria-checked"),
    ("ellipse", "aria-colcount"),
    ("ellipse", "aria-colindex"),
    ("ellipse", "aria-colspan"),
    ("ellipse", "aria-controls"),
    ("ellipse", "aria-current"),
    ("ellipse", "aria-describedby"),
    ("ellipse", "aria-details"),
    ("ellipse", "aria-disabled"),
    ("ellipse", "aria-dropeffect"),
    ("ellipse", "aria-errormessage"),
    ("ellipse", "aria-expanded"),
    ("ellipse", "aria-flowto"),
    ("ellipse", "aria-grabbed"),
    ("ellipse", "aria-haspopup"),
    ("ellipse", "aria-hidden"),
    ("ellipse", "aria-invalid"),
    ("ellipse", "aria-keyshortcuts"),
    ("ellipse", "aria-label"),
    ("ellipse", "aria-labelledby"),
    ("ellipse", "aria-level"),
    ("ellipse", "aria-live"),
    ("ellipse", "aria-modal"),
    ("ellipse", "aria-multiline"),
    ("ellipse", "aria-multiselectable"),
    ("ellipse", "aria-orientation"),
    ("ellipse", "aria-owns"),
    ("ellipse", "aria-placeholder"),
    ("ellipse", "aria-posinset"),
    ("ellipse", "aria-pressed"),
    ("ellipse", "aria-readonly"),
    ("ellipse", "aria-relevant"),
    ("ellipse", "aria-required"),
    ("ellipse", "aria-roledescription"),
    ("ellipse", "aria-rowcount"),
    ("ellipse", "aria-rowindex"),
    ("ellipse", "aria-rowspan"),
    ("ellipse", "aria-selected"),
    ("ellipse", "aria-setsize"),
    ("ellipse", "aria-sort"),
    ("ellipse", "aria-valuemax"),
    ("ellipse", "aria-valuemin"),
    ("ellipse", "aria-valuenow"),
    ("ellipse", "aria-valuetext"),
    ("ellipse", "pathLength"),
    ("ellipse", "requiredExtensions"),
    ("ellipse", "role"),
    ("ellipse", "systemLanguage"),
    ("embed", "height"),
    ("embed", "src"),
    ("embed", "type"),
    ("embed", "width"),
    ("feBlend", "height"),
    ("feBlend", "in"),
    ("feBlend", "in2"),
    ("feBlend", "mode"),
    ("feBlend", "result"),
    ("feBlend", "width"),
    ("feBlend", "x"),
    ("feBlend", "y"),
    ("feColorMatrix", "height"),
    ("feColorMatrix", "in"),
    ("feColorMatrix", "result"),
    ("feColorMatrix", "type"),
    ("feColorMatrix", "values"),
    ("feColorMatrix", "width"),
    ("feColorMatrix", "x"),
    ("feColorMatrix", "y"),
    ("feComponentTransfer", "height"),
    ("feComponentTransfer", "in"),
    ("feComponentTransfer", "result"),
    ("feComponentTransfer", "width"),
    ("feComponentTransfer", "x"),
    ("feComponentTransfer", "y"),
    ("feComposite", "height"),
    ("feComposite", "in"),
    ("feComposite", "in2"),
    ("feComposite", "k1"),
    ("feComposite", "k2"),
    ("feComposite", "k3"),
    ("feComposite", "k4"),
    ("feComposite", "operator"),
    ("feComposite", "result"),
    ("feComposite", "width"),
    ("feComposite", "x"),
    ("feComposite", "y"),
    ("feConvolveMatrix", "bias"),
    ("feConvolveMatrix", "divisor"),
    ("feConvolveMatrix", "edgeMode"),
    ("feConvolveMatrix", "height"),
    ("feConvolveMatrix", "in"),
    ("feConvolveMatrix", "kernelMatrix"),
    ("feConvolveMatrix", "kernelUnitLength"),
    ("feConvolveMatrix", "order"),
    ("feConvolveMatrix", "preserveAlpha"),
    ("feConvolveMatrix", "result"),
    ("feConvolveMatrix", "targetX"),
    ("feConvolveMatrix", "targetY"),
    ("feConvolveMatrix", "width"),
    ("feConvolveMatrix", "x"),
    ("feConvolveMatrix", "y"),
    ("feDiffuseLighting", "diffuseConstant"),
    ("feDiffuseLighting", "height"),
    ("feDiffuseLighting", "in"),
    ("feDiffuseLighting", "kernelUnitLength"),
    ("feDiffuseLighting", "result"),
    ("feDiffuseLighting", "surfaceScale"),
    ("feDiffuseLighting", "width"),
    ("feDiffuseLighting", "x"),
    ("feDiffuseLighting", "y"),
    ("feDisplacementMap", "height"),
    ("feDisplacementMap", "in"),
    ("feDisplacementMap", "in2"),
    ("feDisplacementMap", "result"),
    ("feDisplacementMap", "scale"),
    ("feDisplacementMap", "width"),
    ("feDisplacementMap", "x"),
    ("feDisplacementMap", "xChannelSelector"),
    ("feDisplacementMap", "y"),
    ("feDisplacementMap", "yChannelSelector"),
    ("feDistantLight", "azimuth"),
    ("feDistantLight", "elevation"),
    ("feDropShadow", "dx"),
    ("feDropShadow", "dy"),
    ("feDropShadow", "height"),
    ("feDropShadow", "in"),
    ("feDropShadow", "result"),
    ("feDropShadow", "stdDeviation"),
    ("feDropShadow", "width"),
    ("feDropShadow", "x"),
    ("feDropShadow", "y"),
    ("feFlood", "height"),
    ("feFlood", "result"),
    ("feFlood", "width"),
    ("feFlood", "x"),
    ("feFlood", "y"),
    ("feFuncA", "amplitude"),
    ("feFuncA", "exponent"),
    ("feFuncA", "intercept"),
    ("feFuncA", "offset"),
    ("feFuncA", "slope"),
    ("feFuncA", "tableValues"),
    ("feFuncA", "type"),
    ("feFuncB", "amplitude"),
    ("feFuncB", "exponent"),
    ("feFuncB", "intercept"),
    ("feFuncB", "offset"),
    ("feFuncB", "slope"),
    ("feFuncB", "tableValues"),
    ("feFuncB", "type"),
    ("feFuncG", "amplitude"),
    ("feFuncG", "exponent"),
    ("feFuncG", "intercept"),
    ("feFuncG", "offset"),
    ("feFuncG", "slope"),
    ("feFuncG", "tableValues"),
    ("feFuncG", "type"),
    ("feFuncR", "amplitude"),
    ("feFuncR", "exponent"),
    ("feFuncR", "intercept"),
    ("feFuncR", "offset"),
    ("feFuncR", "slope"),
    ("feFuncR", "tableValues"),
    ("feFuncR", "type"),
    ("feGaussianBlur", "edgeMode"),
    ("feGaussianBlur", "height"),
    ("feGaussianBlur", "in"),
    ("feGaussianBlur", "result"),
    ("feGaussianBlur", "stdDeviation"),
    ("feGaussianBlur", "width"),
    ("feGaussianBlur", "x"),
    ("feGaussianBlur", "y"),
    ("feImage", "crossorigin"),
    ("feImage", "height"),
    ("feImage", "href"),
    ("feImage", "preserveAspectRatio"),
    ("feImage", "result"),
    ("feImage", "width"),
    ("feImage", "x"),
    ("feImage", "y"),
    ("feMerge", "height"),
    ("feMerge", "result"),
    ("feMerge", "width"),
    ("feMerge", "x"),
    ("feMerge", "y"),
    ("feMergeNode", "in"),
    ("feMorphology", "height"),
    ("feMorphology", "in"),
    ("feMorphology", "operator"),
    ("feMorphology", "radius"),
    ("feMorphology", "result"),
    ("feMorphology", "width"),
    ("feMorphology", "x"),
    ("feMorphology", "y"),
    ("feOffset", "dx"),
    ("feOffset", "dy"),
    ("feOffset", "height"),
    ("feOffset", "in"),
    ("feOffset", "result"),
    ("feOffset", "width"),
    ("feOffset", "x"),
    ("feOffset", "y"),
    ("fePointLight", "x"),
    ("fePointLight", "y"),
    ("fePointLight", "z"),
    ("feSpecularLighting", "height"),
    ("feSpecularLighting", "in"),
    ("feSpecularLighting", "kernelUnitLength"),
    ("feSpecularLighting", "result"),
    ("feSpecularLighting", "specularConstant"),
    ("feSpecularLighting", "specularExponent"),
    ("feSpecularLighting", "surfaceScale"),
    ("feSpecularLighting", "width"),
    ("feSpecularLighting", "x"),
    ("feSpecularLighting", "y"),
    ("feSpotLight", "limitingConeAngle"),
    ("feSpotLight", "pointsAtX"),
    ("feSpotLight", "pointsAtY"),
    ("feSpotLight", "pointsAtZ"),
    ("feSpotLight", "specularExponent"),
    ("feSpotLight", "x"),
    ("feSpotLight", "y"),
    ("feSpotLight", "z"),
    ("feTile", "height"),
    ("feTile", "in"),
    ("feTile", "result"),
    ("feTile", "width"),
    ("feTile", "x"),
    ("feTile", "y"),
    ("feTurbulence", "baseFrequency"),
    ("feTurbulence", "height"),
    ("feTurbulence", "numOctaves"),
    ("feTurbulence", "result"),
    ("feTurbulence", "seed"),
    ("feTurbulence", "stitchTiles"),
    ("feTurbulence", "type"),
    ("feTurbulence", "width"),
    ("feTurbulence", "x"),
    ("feTurbulence", "y"),
    ("fieldset", "disabled"),
    ("fieldset", "form"),
    ("fieldset", "name"),
    ("filter", "filterUnits"),
    ("filter", "height"),
    ("filter", "primitiveUnits"),
    ("filter", "width"),
    ("filter", "x"),
    ("filter", "y"),
    ("foreignObject", "aria-activedescendant"),
    ("foreignObject", "aria-atomic"),
    ("foreignObject", "aria-autocomplete"),
    ("foreignObject", "aria-busy"),
    ("foreignObject", "aria-checked"),
    ("foreignObject", "aria-colcount"),
    ("foreignObject", "aria-colindex"),
    ("foreignObject", "aria-colspan"),
    ("foreignObject", "aria-controls"),
    ("foreignObject", "aria-current"),
    ("foreignObject", "aria-describedby"),
    ("foreignObject", "aria-details"),
    ("foreignObject", "aria-disabled"),
    ("foreignObject", "aria-dropeffect"),
    ("foreignObject", "aria-errormessage"),
    ("foreignObject", "aria-expanded"),
    ("foreignObject", "aria-flowto"),
    ("foreignObject", "aria-grabbed"),
    ("foreignObject", "aria-haspopup"),
    ("foreignObject", "aria-hidden"),
    ("foreignObject", "aria-invalid"),
    ("foreignObject", "aria-keyshortcuts"),
    ("foreignObject", "aria-label"),
    ("foreignObject", "aria-labelledby"),
    ("foreignObject", "aria-level"),
    ("foreignObject", "aria-live"),
    ("foreignObject", "aria-modal"),
    ("foreignObject", "aria-multiline"),
    ("foreignObject", "aria-multiselectable"),
    ("foreignObject", "aria-orientation"),
    ("foreignObject", "aria-owns"),
    ("foreignObject", "aria-placeholder"),
    ("foreignObject", "aria-posinset"),
    ("foreignObject", "aria-pressed"),
    ("foreignObject", "aria-readonly"),
    ("foreignObject", "aria-relevant"),
    ("foreignObject", "aria-required"),
    ("foreignObject", "aria-roledescription"),
    ("foreignObject", "aria-rowcount"),
    ("foreignObject", "aria-rowindex"),
    ("foreignObject", "aria-rowspan"),
    ("foreignObject", "aria-selected"),
    ("foreignObject", "aria-setsize"),
    ("foreignObject", "aria-sort"),
    ("foreignObject", "aria-valuemax"),
    ("foreignObject", "aria-valuemin"),
    ("foreignObject", "aria-valuenow"),
    ("foreignObject", "aria-valuetext"),
    ("foreignObject", "requiredExtensions"),
    ("foreignObject", "role"),
    ("foreignObject", "systemLanguage"),
    ("form", "accept-charset"),
    ("form", "action"),
    ("form", "autocomplete"),
    ("form", "enctype"),
    ("form", "method"),
    ("form", "name"),
    ("form", "novalidate"),
    ("form", "target"),
    ("g", "aria-activedescendant"),
    ("g", "aria-atomic"),
    ("g", "aria-autocomplete"),
    ("g", "aria-busy"),
    ("g", "aria-checked"),
    ("g", "aria-colcount"),
    ("g", "aria-colindex"),
    ("g", "aria-colspan"),
    ("g", "aria-controls"),
    ("g", "aria-current"),
    ("g", "aria-describedby"),
    ("g", "aria-details"),
    ("g", "aria-disabled"),
    ("g", "aria-dropeffect"),
    ("g", "aria-errormessage"),
    ("g", "aria-expanded"),
    ("g", "aria-flowto"),
    ("g", "aria-grabbed"),
    ("g", "aria-haspopup"),
    ("g", "aria-hidden"),
    ("g", "aria-invalid"),
    ("g", "aria-keyshortcuts"),
    ("g", "aria-label"),
    ("g", "aria-labelledby"),
    ("g", "aria-level"),
    ("g", "aria-live"),
    ("g", "aria-modal"),
    ("g", "aria-multiline"),
    ("g", "aria-multiselectable"),
    ("g", "aria-orientation"),
    ("g", "aria-owns"),
    ("g", "aria-placeholder"),
    ("g", "aria-posinset"),
    ("g", "aria-pressed"),
    ("g", "aria-readonly"),
    ("g", "aria-relevant"),
    ("g", "aria-required"),
    ("g", "aria-roledescription"),
    ("g", "aria-rowcount"),
    ("g", "aria-rowindex"),
    ("g", "aria-rowspan"),
    ("g", "aria-selected"),
    ("g", "aria-setsize"),
    ("g", "aria-sort"),
    ("g", "aria-valuemax"),
    ("g", "aria-valuemin"),
    ("g", "aria-valuenow"),
    ("g", "aria-valuetext"),
    ("g", "requiredExtensions"),
    ("g", "role"),
    ("g", "systemLanguage"),
    ("iframe", "allow"),
    ("iframe", "allowfullscreen"),
    ("iframe", "height"),
    ("iframe", "loading"),
    ("iframe", "name"),
    ("iframe", "referrerpolicy"),
    ("iframe", "sandbox"),
    ("iframe", "src"),
    ("iframe", "srcdoc"),
    ("iframe", "width"),
    ("image", "aria-activedescendant"),
    ("image", "aria-atomic"),
    ("image", "aria-autocomplete"),
    ("image", "aria-busy"),
    ("image", "aria-checked"),
    ("image", "aria-colcount"),
    ("image", "aria-colindex"),
    ("image", "aria-colspan"),
    ("image", "aria-controls"),
    ("image", "aria-current"),
    ("image", "aria-describedby"),
    ("image", "aria-details"),
    ("image", "aria-disabled"),
    ("image", "aria-dropeffect"),
    ("image", "aria-errormessage"),
    ("image", "aria-expanded"),
    ("image", "aria-flowto"),
    ("image", "aria-grabbed"),
    ("image", "aria-haspopup"),
    ("image", "aria-hidden"),
    ("image", "aria-invalid"),
    ("image", "aria-keyshortcuts"),
    ("image", "aria-label"),
    ("image", "aria-labelledby"),
    ("image", "aria-level"),
    ("image", "aria-live"),
    ("image", "aria-modal"),
    ("image", "aria-multiline"),
    ("image", "aria-multiselectable"),
    ("image", "aria-orientation"),
    ("image", "aria-owns"),
    ("image", "aria-placeholder"),
    ("image", "aria-posinset"),
    ("image", "aria-pressed"),
    ("image", "aria-readonly"),
    ("image", "aria-relevant"),
    ("image", "aria-required"),
    ("image", "aria-roledescription"),
    ("image", "aria-rowcount"),
    ("image", "aria-rowindex"),
    ("image", "aria-rowspan"),
    ("image", "aria-selected"),
    ("image", "aria-setsize"),
    ("image", "aria-sort"),
    ("image", "aria-valuemax"),
    ("image", "aria-valuemin"),
    ("image", "aria-valuenow"),
    ("image", "aria-valuetext"),
    ("image", "crossorigin"),
    ("image", "href"),
    ("image", "preserveAspectRatio"),
    ("image", "requiredExtensions"),
    ("image", "role"),
    ("image", "systemLanguage"),
    ("img", "alt"),
    ("img", "controls"),
    ("img", "crossorigin"),
    ("img", "decoding"),
    ("img", "fetchpriority"),
    ("img", "height"),
    ("img", "ismap"),
    ("img", "loading"),
    ("img", "referrerpolicy"),
    ("img", "sizes"),
    ("img", "src"),
    ("img", "srcset"),
    ("img", "usemap"),
    ("img", "width"),
    ("input", "accept"),
    ("input", "alpha"),
    ("input", "alt"),
    ("input", "autocomplete"),
    ("input", "checked"),
    ("input", "colorspace"),
    ("input", "dirname"),
    ("input", "disabled"),
    ("input", "form"),
    ("input", "formaction"),
    ("input", "formenctype"),
    ("input", "formmethod"),
    ("input", "formnovalidate"),
    ("input", "formtarget"),
    ("input", "height"),
    ("input", "list"),
    ("input", "max"),
    ("input", "maxlength"),
    ("input", "min"),
    ("input", "minlength"),
    ("input", "multiple"),
    ("input", "name"),
    ("input", "pattern"),
    ("input", "placeholder"),
    ("input", "popovertarget"),
    ("input", "popovertargetaction"),
    ("input", "readonly"),
    ("input", "required"),
    ("input", "size"),
    ("input", "src"),
    ("input", "step"),
    ("input", "type"),
    ("input", "value"),
    ("input", "width"),
    ("ins", "cite"),
    ("ins", "datetime"),
    ("label", "for"),
    ("li", "value"),
    ("line", "aria-activedescendant"),
    ("line", "aria-atomic"),
    ("line", "aria-autocomplete"),
    ("line", "aria-busy"),
    ("line", "aria-checked"),
    ("line", "aria-colcount"),
    ("line", "aria-colindex"),
    ("line", "aria-colspan"),
    ("line", "aria-controls"),
    ("line", "aria-current"),
    ("line", "aria-describedby"),
    ("line", "aria-details"),
    ("line", "aria-disabled"),
    ("line", "aria-dropeffect"),
    ("line", "aria-errormessage"),
    ("line", "aria-expanded"),
    ("line", "aria-flowto"),
    ("line", "aria-grabbed"),
    ("line", "aria-haspopup"),
    ("line", "aria-hidden"),
    ("line", "aria-invalid"),
    ("line", "aria-keyshortcuts"),
    ("line", "aria-label"),
    ("line", "aria-labelledby"),
    ("line", "aria-level"),
    ("line", "aria-live"),
    ("line", "aria-modal"),
    ("line", "aria-multiline"),
    ("line", "aria-multiselectable"),
    ("line", "aria-orientation"),
    ("line", "aria-owns"),
    ("line", "aria-placeholder"),
    ("line", "aria-posinset"),
    ("line", "aria-pressed"),
    ("line", "aria-readonly"),
    ("line", "aria-relevant"),
    ("line", "aria-required"),
    ("line", "aria-roledescription"),
    ("line", "aria-rowcount"),
    ("line", "aria-rowindex"),
    ("line", "aria-rowspan"),
    ("line", "aria-selected"),
    ("line", "aria-setsize"),
    ("line", "aria-sort"),
    ("line", "aria-valuemax"),
    ("line", "aria-valuemin"),
    ("line", "aria-valuenow"),
    ("line", "aria-valuetext"),
    ("line", "pathLength"),
    ("line", "requiredExtensions"),
    ("line", "role"),
    ("line", "systemLanguage"),
    ("line", "x1"),
    ("line", "x2"),
    ("line", "y1"),
    ("line", "y2"),
    ("linearGradient", "gradientTransform"),
    ("linearGradient", "gradientUnits"),
    ("linearGradient", "href"),
    ("linearGradient", "spreadMethod"),
    ("linearGradient", "x1"),
    ("linearGradient", "x2"),
    ("linearGradient", "y1"),
    ("linearGradient", "y2"),
    ("link", "as"),
    ("link", "blocking"),
    ("link", "color"),
    ("link", "crossorigin"),
    ("link", "disabled"),
    ("link", "fetchpriority"),
    ("link", "href"),
    ("link", "hreflang"),
    ("link", "imagesizes"),
    ("link", "imagesrcset"),
    ("link", "integrity"),
    ("link", "media"),
    ("link", "referrerpolicy"),
    ("link", "rel"),
    ("link", "sizes"),
    ("link", "type"),
    ("map", "name"),
    ("marker", "markerHeight"),
    ("marker", "markerUnits"),
    ("marker", "markerWidth"),
    ("marker", "orient"),
    ("marker", "preserveAspectRatio"),
    ("marker", "refX"),
    ("marker", "refY"),
    ("marker", "viewBox"),
    ("mask", "height"),
    ("mask", "maskContentUnits"),
    ("mask", "maskUnits"),
    ("mask", "requiredExtensions"),
    ("mask", "systemLanguage"),
    ("mask", "width"),
    ("mask", "x"),
    ("mask", "y"),
    ("meta", "charset"),
    ("meta", "content"),
    ("meta", "http-equiv"),
    ("meta", "media"),
    ("meta", "name"),
    ("meter", "high"),
    ("meter", "low"),
    ("meter", "max"),
    ("meter", "min"),
    ("meter", "optimum"),
    ("meter", "value"),
    ("mpath", "href"),
    ("object", "data"),
    ("object", "form"),
    ("object", "height"),
    ("object", "name"),
    ("object", "type"),
    ("object", "width"),
    ("ol", "reversed"),
    ("ol", "start"),
    ("ol", "type"),
    ("optgroup", "disabled"),
    ("optgroup", "label"),
    ("option", "disabled"),
    ("option", "label"),
    ("option", "selected"),
    ("option", "value"),
    ("output", "for"),
    ("output", "form"),
    ("output", "name"),
    ("path", "aria-activedescendant"),
    ("path", "aria-atomic"),
    ("path", "aria-autocomplete"),
    ("path", "aria-busy"),
    ("path", "aria-checked"),
    ("path", "aria-colcount"),
    ("path", "aria-colindex"),
    ("path", "aria-colspan"),
    ("path", "aria-controls"),
    ("path", "aria-current"),
    ("path", "aria-describedby"),
    ("path", "aria-details"),
    ("path", "aria-disabled"),
    ("path", "aria-dropeffect"),
    ("path", "aria-errormessage"),
    ("path", "aria-expanded"),
    ("path", "aria-flowto"),
    ("path", "aria-grabbed"),
    ("path", "aria-haspopup"),
    ("path", "aria-hidden"),
    ("path", "aria-invalid"),
    ("path", "aria-keyshortcuts"),
    ("path", "aria-label"),
    ("path", "aria-labelledby"),
    ("path", "aria-level"),
    ("path", "aria-live"),
    ("path", "aria-modal"),
    ("path", "aria-multiline"),
    ("path", "aria-multiselectable"),
    ("path", "aria-orientation"),
    ("path", "aria-owns"),
    ("path", "aria-placeholder"),
    ("path", "aria-posinset"),
    ("path", "aria-pressed"),
    ("path", "aria-readonly"),
    ("path", "aria-relevant"),
    ("path", "aria-required"),
    ("path", "aria-roledescription"),
    ("path", "aria-rowcount"),
    ("path", "aria-rowindex"),
    ("path", "aria-rowspan"),
    ("path", "aria-selected"),
    ("path", "aria-setsize"),
    ("path", "aria-sort"),
    ("path", "aria-valuemax"),
    ("path", "aria-valuemin"),
    ("path", "aria-valuenow"),
    ("path", "aria-valuetext"),
    ("path", "pathLength"),
    ("path", "requiredExtensions"),
    ("path", "role"),
    ("path", "systemLanguage"),
    ("pattern", "height"),
    ("pattern", "href"),
    ("pattern", "patternContentUnits"),
    ("pattern", "patternTransform"),
    ("pattern", "patternUnits"),
    ("pattern", "preserveAspectRatio"),
    ("pattern", "viewBox"),
    ("pattern", "width"),
    ("pattern", "x"),
    ("pattern", "y"),
    ("picture", "height"),
    ("picture", "width"),
    ("polygon", "aria-activedescendant"),
    ("polygon", "aria-atomic"),
    ("polygon", "aria-autocomplete"),
    ("polygon", "aria-busy"),
    ("polygon", "aria-checked"),
    ("polygon", "aria-colcount"),
    ("polygon", "aria-colindex"),
    ("polygon", "aria-colspan"),
    ("polygon", "aria-controls"),
    ("polygon", "aria-current"),
    ("polygon", "aria-describedby"),
    ("polygon", "aria-details"),
    ("polygon", "aria-disabled"),
    ("polygon", "aria-dropeffect"),
    ("polygon", "aria-errormessage"),
    ("polygon", "aria-expanded"),
    ("polygon", "aria-flowto"),
    ("polygon", "aria-grabbed"),
    ("polygon", "aria-haspopup"),
    ("polygon", "aria-hidden"),
    ("polygon", "aria-invalid"),
    ("polygon", "aria-keyshortcuts"),
    ("polygon", "aria-label"),
    ("polygon", "aria-labelledby"),
    ("polygon", "aria-level"),
    ("polygon", "aria-live"),
    ("polygon", "aria-modal"),
    ("polygon", "aria-multiline"),
    ("polygon", "aria-multiselectable"),
    ("polygon", "aria-orientation"),
    ("polygon", "aria-owns"),
    ("polygon", "aria-placeholder"),
    ("polygon", "aria-posinset"),
    ("polygon", "aria-pressed"),
    ("polygon", "aria-readonly"),
    ("polygon", "aria-relevant"),
    ("polygon", "aria-required"),
    ("polygon", "aria-roledescription"),
    ("polygon", "aria-rowcount"),
    ("polygon", "aria-rowindex"),
    ("polygon", "aria-rowspan"),
    ("polygon", "aria-selected"),
    ("polygon", "aria-setsize"),
    ("polygon", "aria-sort"),
    ("polygon", "aria-valuemax"),
    ("polygon", "aria-valuemin"),
    ("polygon", "aria-valuenow"),
    ("polygon", "aria-valuetext"),
    ("polygon", "pathLength"),
    ("polygon", "points"),
    ("polygon", "requiredExtensions"),
    ("polygon", "role"),
    ("polygon", "systemLanguage"),
    ("polyline", "aria-activedescendant"),
    ("polyline", "aria-atomic"),
    ("polyline", "aria-autocomplete"),
    ("polyline", "aria-busy"),
    ("polyline", "aria-checked"),
    ("polyline", "aria-colcount"),
    ("polyline", "aria-colindex"),
    ("polyline", "aria-colspan"),
    ("polyline", "aria-controls"),
    ("polyline", "aria-current"),
    ("polyline", "aria-describedby"),
    ("polyline", "aria-details"),
    ("polyline", "aria-disabled"),
    ("polyline", "aria-dropeffect"),
    ("polyline", "aria-errormessage"),
    ("polyline", "aria-expanded"),
    ("polyline", "aria-flowto"),
    ("polyline", "aria-grabbed"),
    ("polyline", "aria-haspopup"),
    ("polyline", "aria-hidden"),
    ("polyline", "aria-invalid"),
    ("polyline", "aria-keyshortcuts"),
    ("polyline", "aria-label"),
    ("polyline", "aria-labelledby"),
    ("polyline", "aria-level"),
    ("polyline", "aria-live"),
    ("polyline", "aria-modal"),
    ("polyline", "aria-multiline"),
    ("polyline", "aria-multiselectable"),
    ("polyline", "aria-orientation"),
    ("polyline", "aria-owns"),
    ("polyline", "aria-placeholder"),
    ("polyline", "aria-posinset"),
    ("polyline", "aria-pressed"),
    ("polyline", "aria-readonly"),
    ("polyline", "aria-relevant"),
    ("polyline", "aria-required"),
    ("polyline", "aria-roledescription"),
    ("polyline", "aria-rowcount"),
    ("polyline", "aria-rowindex"),
    ("polyline", "aria-rowspan"),
    ("polyline", "aria-selected"),
    ("polyline", "aria-setsize"),
    ("polyline", "aria-sort"),
    ("polyline", "aria-valuemax"),
    ("polyline", "aria-valuemin"),
    ("polyline", "aria-valuenow"),
    ("polyline", "aria-valuetext"),
    ("polyline", "pathLength"),
    ("polyline", "points"),
    ("polyline", "requiredExtensions"),
    ("polyline", "role"),
    ("polyline", "systemLanguage"),
    ("progress", "max"),
    ("progress", "value"),
    ("q", "cite"),
    ("radialGradient", "cx"),
    ("radialGradient", "cy"),
    ("radialGradient", "fr"),
    ("radialGradient", "fx"),
    ("radialGradient", "fy"),
    ("radialGradient", "gradientTransform"),
    ("radialGradient", "gradientUnits"),
    ("radialGradient", "href"),
    ("radialGradient", "r"),
    ("radialGradient", "spreadMethod"),
    ("rect", "aria-activedescendant"),
    ("rect", "aria-atomic"),
    ("rect", "aria-autocomplete"),
    ("rect", "aria-busy"),
    ("rect", "aria-checked"),
    ("rect", "aria-colcount"),
    ("rect", "aria-colindex"),
    ("rect", "aria-colspan"),
    ("rect", "aria-controls"),
    ("rect", "aria-current"),
    ("rect", "aria-describedby"),
    ("rect", "aria-details"),
    ("rect", "aria-disabled"),
    ("rect", "aria-dropeffect"),
    ("rect", "aria-errormessage"),
    ("rect", "aria-expanded"),
    ("rect", "aria-flowto"),
    ("rect", "aria-grabbed"),
    ("rect", "aria-haspopup"),
    ("rect", "aria-hidden"),
    ("rect", "aria-invalid"),
    ("rect", "aria-keyshortcuts"),
    ("rect", "aria-label"),
    ("rect", "aria-labelledby"),
    ("rect", "aria-level"),
    ("rect", "aria-live"),
    ("rect", "aria-modal"),
    ("rect", "aria-multiline"),
    ("rect", "aria-multiselectable"),
    ("rect", "aria-orientation"),
    ("rect", "aria-owns"),
    ("rect", "aria-placeholder"),
    ("rect", "aria-posinset"),
    ("rect", "aria-pressed"),
    ("rect", "aria-readonly"),
    ("rect", "aria-relevant"),
    ("rect", "aria-required"),
    ("rect", "aria-roledescription"),
    ("rect", "aria-rowcount"),
    ("rect", "aria-rowindex"),
    ("rect", "aria-rowspan"),
    ("rect", "aria-selected"),
    ("rect", "aria-setsize"),
    ("rect", "aria-sort"),
    ("rect", "aria-valuemax"),
    ("rect", "aria-valuemin"),
    ("rect", "aria-valuenow"),
    ("rect", "aria-valuetext"),
    ("rect", "pathLength"),
    ("rect", "requiredExtensions"),
    ("rect", "role"),
    ("rect", "systemLanguage"),
    ("script", "async"),
    ("script", "blocking"),
    ("script", "crossorigin"),
    ("script", "defer"),
    ("script", "fetchpriority"),
    ("script", "integrity"),
    ("script", "nomodule"),
    ("script", "referrerpolicy"),
    ("script", "src"),
    ("script", "type"),
    ("select", "autocomplete"),
    ("select", "disabled"),
    ("select", "form"),
    ("select", "multiple"),
    ("select", "name"),
    ("select", "required"),
    ("select", "size"),
    ("set", "attributeName"),
    ("set", "begin"),
    ("set", "dur"),
    ("set", "end"),
    ("set", "href"),
    ("set", "max"),
    ("set", "min"),
    ("set", "repeatCount"),
    ("set", "repeatDur"),
    ("set", "requiredExtensions"),
    ("set", "restart"),
    ("set", "systemLanguage"),
    ("set", "to"),
    ("slot", "name"),
    ("source", "height"),
    ("source", "media"),
    ("source", "sizes"),
    ("source", "src"),
    ("source", "srcset"),
    ("source", "type"),
    ("source", "width"),
    ("stop", "offset"),
    ("style", "blocking"),
    ("style", "media"),
    ("svg", "aria-activedescendant"),
    ("svg", "aria-atomic"),
    ("svg", "aria-autocomplete"),
    ("svg", "aria-busy"),
    ("svg", "aria-checked"),
    ("svg", "aria-colcount"),
    ("svg", "aria-colindex"),
    ("svg", "aria-colspan"),
    ("svg", "aria-controls"),
    ("svg", "aria-current"),
    ("svg", "aria-describedby"),
    ("svg", "aria-details"),
    ("svg", "aria-disabled"),
    ("svg", "aria-dropeffect"),
    ("svg", "aria-errormessage"),
    ("svg", "aria-expanded"),
    ("svg", "aria-flowto"),
    ("svg", "aria-grabbed"),
    ("svg", "aria-haspopup"),
    ("svg", "aria-hidden"),
    ("svg", "aria-invalid"),
    ("svg", "aria-keyshortcuts"),
    ("svg", "aria-label"),
    ("svg", "aria-labelledby"),
    ("svg", "aria-level"),
    ("svg", "aria-live"),
    ("svg", "aria-modal"),
    ("svg", "aria-multiline"),
    ("svg", "aria-multiselectable"),
    ("svg", "aria-orientation"),
    ("svg", "aria-owns"),
    ("svg", "aria-placeholder"),
    ("svg", "aria-posinset"),
    ("svg", "aria-pressed"),
    ("svg", "aria-readonly"),
    ("svg", "aria-relevant"),
    ("svg", "aria-required"),
    ("svg", "aria-roledescription"),
    ("svg", "aria-rowcount"),
    ("svg", "aria-rowindex"),
    ("svg", "aria-rowspan"),
    ("svg", "aria-selected"),
    ("svg", "aria-setsize"),
    ("svg", "aria-sort"),
    ("svg", "aria-valuemax"),
    ("svg", "aria-valuemin"),
    ("svg", "aria-valuenow"),
    ("svg", "aria-valuetext"),
    ("svg", "playbackorder"),
    ("svg", "preserveAspectRatio"),
    ("svg", "requiredExtensions"),
    ("svg", "role"),
    ("svg", "systemLanguage"),
    ("svg", "timelinebegin"),
    ("svg", "viewBox"),
    ("svg", "zoomAndPan"),
    ("switch", "aria-activedescendant"),
    ("switch", "aria-atomic"),
    ("switch", "aria-autocomplete"),
    ("switch", "aria-busy"),
    ("switch", "aria-checked"),
    ("switch", "aria-colcount"),
    ("switch", "aria-colindex"),
    ("switch", "aria-colspan"),
    ("switch", "aria-controls"),
    ("switch", "aria-current"),
    ("switch", "aria-describedby"),
    ("switch", "aria-details"),
    ("switch", "aria-disabled"),
    ("switch", "aria-dropeffect"),
    ("switch", "aria-errormessage"),
    ("switch", "aria-expanded"),
    ("switch", "aria-flowto"),
    ("switch", "aria-grabbed"),
    ("switch", "aria-haspopup"),
    ("switch", "aria-hidden"),
    ("switch", "aria-invalid"),
    ("switch", "aria-keyshortcuts"),
    ("switch", "aria-label"),
    ("switch", "aria-labelledby"),
    ("switch", "aria-level"),
    ("switch", "aria-live"),
    ("switch", "aria-modal"),
    ("switch", "aria-multiline"),
    ("switch", "aria-multiselectable"),
    ("switch", "aria-orientation"),
    ("switch", "aria-owns"),
    ("switch", "aria-placeholder"),
    ("switch", "aria-posinset"),
    ("switch", "aria-pressed"),
    ("switch", "aria-readonly"),
    ("switch", "aria-relevant"),
    ("switch", "aria-required"),
    ("switch", "aria-roledescription"),
    ("switch", "aria-rowcount"),
    ("switch", "aria-rowindex"),
    ("switch", "aria-rowspan"),
    ("switch", "aria-selected"),
    ("switch", "aria-setsize"),
    ("switch", "aria-sort"),
    ("switch", "aria-valuemax"),
    ("switch", "aria-valuemin"),
    ("switch", "aria-valuenow"),
    ("switch", "aria-valuetext"),
    ("switch", "requiredExtensions"),
    ("switch", "role"),
    ("switch", "systemLanguage"),
    ("symbol", "aria-activedescendant"),
    ("symbol", "aria-atomic"),
    ("symbol", "aria-autocomplete"),
    ("symbol", "aria-busy"),
    ("symbol", "aria-checked"),
    ("symbol", "aria-colcount"),
    ("symbol", "aria-colindex"),
    ("symbol", "aria-colspan"),
    ("symbol", "aria-controls"),
    ("symbol", "aria-current"),
    ("symbol", "aria-describedby"),
    ("symbol", "aria-details"),
    ("symbol", "aria-disabled"),
    ("symbol", "aria-dropeffect"),
    ("symbol", "aria-errormessage"),
    ("symbol", "aria-expanded"),
    ("symbol", "aria-flowto"),
    ("symbol", "aria-grabbed"),
    ("symbol", "aria-haspopup"),
    ("symbol", "aria-hidden"),
    ("symbol", "aria-invalid"),
    ("symbol", "aria-keyshortcuts"),
    ("symbol", "aria-label"),
    ("symbol", "aria-labelledby"),
    ("symbol", "aria-level"),
    ("symbol", "aria-live"),
    ("symbol", "aria-modal"),
    ("symbol", "aria-multiline"),
    ("symbol", "aria-multiselectable"),
    ("symbol", "aria-orientation"),
    ("symbol", "aria-owns"),
    ("symbol", "aria-placeholder"),
    ("symbol", "aria-posinset"),
    ("symbol", "aria-pressed"),
    ("symbol", "aria-readonly"),
    ("symbol", "aria-relevant"),
    ("symbol", "aria-required"),
    ("symbol", "aria-roledescription"),
    ("symbol", "aria-rowcount"),
    ("symbol", "aria-rowindex"),
    ("symbol", "aria-rowspan"),
    ("symbol", "aria-selected"),
    ("symbol", "aria-setsize"),
    ("symbol", "aria-sort"),
    ("symbol", "aria-valuemax"),
    ("symbol", "aria-valuemin"),
    ("symbol", "aria-valuenow"),
    ("symbol", "aria-valuetext"),
    ("symbol", "preserveAspectRatio"),
    ("symbol", "refX"),
    ("symbol", "refY"),
    ("symbol", "role"),
    ("symbol", "viewBox"),
    ("td", "colspan"),
    ("td", "headers"),
    ("td", "rowspan"),
    ("template", "for"),
    ("template", "shadowrootclonable"),
    ("template", "shadowrootcustomelementregistry"),
    ("template", "shadowrootdelegatesfocus"),
    ("template", "shadowrootmode"),
    ("template", "shadowrootserializable"),
    ("template", "shadowrootslotassignment"),
    ("text", "aria-activedescendant"),
    ("text", "aria-atomic"),
    ("text", "aria-autocomplete"),
    ("text", "aria-busy"),
    ("text", "aria-checked"),
    ("text", "aria-colcount"),
    ("text", "aria-colindex"),
    ("text", "aria-colspan"),
    ("text", "aria-controls"),
    ("text", "aria-current"),
    ("text", "aria-describedby"),
    ("text", "aria-details"),
    ("text", "aria-disabled"),
    ("text", "aria-dropeffect"),
    ("text", "aria-errormessage"),
    ("text", "aria-expanded"),
    ("text", "aria-flowto"),
    ("text", "aria-grabbed"),
    ("text", "aria-haspopup"),
    ("text", "aria-hidden"),
    ("text", "aria-invalid"),
    ("text", "aria-keyshortcuts"),
    ("text", "aria-label"),
    ("text", "aria-labelledby"),
    ("text", "aria-level"),
    ("text", "aria-live"),
    ("text", "aria-modal"),
    ("text", "aria-multiline"),
    ("text", "aria-multiselectable"),
    ("text", "aria-orientation"),
    ("text", "aria-owns"),
    ("text", "aria-placeholder"),
    ("text", "aria-posinset"),
    ("text", "aria-pressed"),
    ("text", "aria-readonly"),
    ("text", "aria-relevant"),
    ("text", "aria-required"),
    ("text", "aria-roledescription"),
    ("text", "aria-rowcount"),
    ("text", "aria-rowindex"),
    ("text", "aria-rowspan"),
    ("text", "aria-selected"),
    ("text", "aria-setsize"),
    ("text", "aria-sort"),
    ("text", "aria-valuemax"),
    ("text", "aria-valuemin"),
    ("text", "aria-valuenow"),
    ("text", "aria-valuetext"),
    ("text", "dx"),
    ("text", "dy"),
    ("text", "lengthAdjust"),
    ("text", "requiredExtensions"),
    ("text", "role"),
    ("text", "rotate"),
    ("text", "systemLanguage"),
    ("text", "textLength"),
    ("text", "x"),
    ("text", "y"),
    ("textPath", "aria-activedescendant"),
    ("textPath", "aria-atomic"),
    ("textPath", "aria-autocomplete"),
    ("textPath", "aria-busy"),
    ("textPath", "aria-checked"),
    ("textPath", "aria-colcount"),
    ("textPath", "aria-colindex"),
    ("textPath", "aria-colspan"),
    ("textPath", "aria-controls"),
    ("textPath", "aria-current"),
    ("textPath", "aria-describedby"),
    ("textPath", "aria-details"),
    ("textPath", "aria-disabled"),
    ("textPath", "aria-dropeffect"),
    ("textPath", "aria-errormessage"),
    ("textPath", "aria-expanded"),
    ("textPath", "aria-flowto"),
    ("textPath", "aria-grabbed"),
    ("textPath", "aria-haspopup"),
    ("textPath", "aria-hidden"),
    ("textPath", "aria-invalid"),
    ("textPath", "aria-keyshortcuts"),
    ("textPath", "aria-label"),
    ("textPath", "aria-labelledby"),
    ("textPath", "aria-level"),
    ("textPath", "aria-live"),
    ("textPath", "aria-modal"),
    ("textPath", "aria-multiline"),
    ("textPath", "aria-multiselectable"),
    ("textPath", "aria-orientation"),
    ("textPath", "aria-owns"),
    ("textPath", "aria-placeholder"),
    ("textPath", "aria-posinset"),
    ("textPath", "aria-pressed"),
    ("textPath", "aria-readonly"),
    ("textPath", "aria-relevant"),
    ("textPath", "aria-required"),
    ("textPath", "aria-roledescription"),
    ("textPath", "aria-rowcount"),
    ("textPath", "aria-rowindex"),
    ("textPath", "aria-rowspan"),
    ("textPath", "aria-selected"),
    ("textPath", "aria-setsize"),
    ("textPath", "aria-sort"),
    ("textPath", "aria-valuemax"),
    ("textPath", "aria-valuemin"),
    ("textPath", "aria-valuenow"),
    ("textPath", "aria-valuetext"),
    ("textPath", "href"),
    ("textPath", "lengthAdjust"),
    ("textPath", "method"),
    ("textPath", "path"),
    ("textPath", "requiredExtensions"),
    ("textPath", "role"),
    ("textPath", "side"),
    ("textPath", "spacing"),
    ("textPath", "startOffset"),
    ("textPath", "systemLanguage"),
    ("textPath", "textLength"),
    ("textarea", "autocomplete"),
    ("textarea", "cols"),
    ("textarea", "dirname"),
    ("textarea", "disabled"),
    ("textarea", "form"),
    ("textarea", "maxlength"),
    ("textarea", "minlength"),
    ("textarea", "name"),
    ("textarea", "placeholder"),
    ("textarea", "readonly"),
    ("textarea", "required"),
    ("textarea", "rows"),
    ("textarea", "wrap"),
    ("th", "abbr"),
    ("th", "colspan"),
    ("th", "headers"),
    ("th", "rowspan"),
    ("th", "scope"),
    ("time", "datetime"),
    ("track", "default"),
    ("track", "kind"),
    ("track", "label"),
    ("track", "src"),
    ("track", "srclang"),
    ("tspan", "aria-activedescendant"),
    ("tspan", "aria-atomic"),
    ("tspan", "aria-autocomplete"),
    ("tspan", "aria-busy"),
    ("tspan", "aria-checked"),
    ("tspan", "aria-colcount"),
    ("tspan", "aria-colindex"),
    ("tspan", "aria-colspan"),
    ("tspan", "aria-controls"),
    ("tspan", "aria-current"),
    ("tspan", "aria-describedby"),
    ("tspan", "aria-details"),
    ("tspan", "aria-disabled"),
    ("tspan", "aria-dropeffect"),
    ("tspan", "aria-errormessage"),
    ("tspan", "aria-expanded"),
    ("tspan", "aria-flowto"),
    ("tspan", "aria-grabbed"),
    ("tspan", "aria-haspopup"),
    ("tspan", "aria-hidden"),
    ("tspan", "aria-invalid"),
    ("tspan", "aria-keyshortcuts"),
    ("tspan", "aria-label"),
    ("tspan", "aria-labelledby"),
    ("tspan", "aria-level"),
    ("tspan", "aria-live"),
    ("tspan", "aria-modal"),
    ("tspan", "aria-multiline"),
    ("tspan", "aria-multiselectable"),
    ("tspan", "aria-orientation"),
    ("tspan", "aria-owns"),
    ("tspan", "aria-placeholder"),
    ("tspan", "aria-posinset"),
    ("tspan", "aria-pressed"),
    ("tspan", "aria-readonly"),
    ("tspan", "aria-relevant"),
    ("tspan", "aria-required"),
    ("tspan", "aria-roledescription"),
    ("tspan", "aria-rowcount"),
    ("tspan", "aria-rowindex"),
    ("tspan", "aria-rowspan"),
    ("tspan", "aria-selected"),
    ("tspan", "aria-setsize"),
    ("tspan", "aria-sort"),
    ("tspan", "aria-valuemax"),
    ("tspan", "aria-valuemin"),
    ("tspan", "aria-valuenow"),
    ("tspan", "aria-valuetext"),
    ("tspan", "dx"),
    ("tspan", "dy"),
    ("tspan", "lengthAdjust"),
    ("tspan", "requiredExtensions"),
    ("tspan", "role"),
    ("tspan", "rotate"),
    ("tspan", "systemLanguage"),
    ("tspan", "textLength"),
    ("tspan", "x"),
    ("tspan", "y"),
    ("unknown", "aria-activedescendant"),
    ("unknown", "aria-atomic"),
    ("unknown", "aria-autocomplete"),
    ("unknown", "aria-busy"),
    ("unknown", "aria-checked"),
    ("unknown", "aria-colcount"),
    ("unknown", "aria-colindex"),
    ("unknown", "aria-colspan"),
    ("unknown", "aria-controls"),
    ("unknown", "aria-current"),
    ("unknown", "aria-describedby"),
    ("unknown", "aria-details"),
    ("unknown", "aria-disabled"),
    ("unknown", "aria-dropeffect"),
    ("unknown", "aria-errormessage"),
    ("unknown", "aria-expanded"),
    ("unknown", "aria-flowto"),
    ("unknown", "aria-grabbed"),
    ("unknown", "aria-haspopup"),
    ("unknown", "aria-hidden"),
    ("unknown", "aria-invalid"),
    ("unknown", "aria-keyshortcuts"),
    ("unknown", "aria-label"),
    ("unknown", "aria-labelledby"),
    ("unknown", "aria-level"),
    ("unknown", "aria-live"),
    ("unknown", "aria-modal"),
    ("unknown", "aria-multiline"),
    ("unknown", "aria-multiselectable"),
    ("unknown", "aria-orientation"),
    ("unknown", "aria-owns"),
    ("unknown", "aria-placeholder"),
    ("unknown", "aria-posinset"),
    ("unknown", "aria-pressed"),
    ("unknown", "aria-readonly"),
    ("unknown", "aria-relevant"),
    ("unknown", "aria-required"),
    ("unknown", "aria-roledescription"),
    ("unknown", "aria-rowcount"),
    ("unknown", "aria-rowindex"),
    ("unknown", "aria-rowspan"),
    ("unknown", "aria-selected"),
    ("unknown", "aria-setsize"),
    ("unknown", "aria-sort"),
    ("unknown", "aria-valuemax"),
    ("unknown", "aria-valuemin"),
    ("unknown", "aria-valuenow"),
    ("unknown", "aria-valuetext"),
    ("unknown", "requiredExtensions"),
    ("unknown", "role"),
    ("unknown", "systemLanguage"),
    ("use", "aria-activedescendant"),
    ("use", "aria-atomic"),
    ("use", "aria-autocomplete"),
    ("use", "aria-busy"),
    ("use", "aria-checked"),
    ("use", "aria-colcount"),
    ("use", "aria-colindex"),
    ("use", "aria-colspan"),
    ("use", "aria-controls"),
    ("use", "aria-current"),
    ("use", "aria-describedby"),
    ("use", "aria-details"),
    ("use", "aria-disabled"),
    ("use", "aria-dropeffect"),
    ("use", "aria-errormessage"),
    ("use", "aria-expanded"),
    ("use", "aria-flowto"),
    ("use", "aria-grabbed"),
    ("use", "aria-haspopup"),
    ("use", "aria-hidden"),
    ("use", "aria-invalid"),
    ("use", "aria-keyshortcuts"),
    ("use", "aria-label"),
    ("use", "aria-labelledby"),
    ("use", "aria-level"),
    ("use", "aria-live"),
    ("use", "aria-modal"),
    ("use", "aria-multiline"),
    ("use", "aria-multiselectable"),
    ("use", "aria-orientation"),
    ("use", "aria-owns"),
    ("use", "aria-placeholder"),
    ("use", "aria-posinset"),
    ("use", "aria-pressed"),
    ("use", "aria-readonly"),
    ("use", "aria-relevant"),
    ("use", "aria-required"),
    ("use", "aria-roledescription"),
    ("use", "aria-rowcount"),
    ("use", "aria-rowindex"),
    ("use", "aria-rowspan"),
    ("use", "aria-selected"),
    ("use", "aria-setsize"),
    ("use", "aria-sort"),
    ("use", "aria-valuemax"),
    ("use", "aria-valuemin"),
    ("use", "aria-valuenow"),
    ("use", "aria-valuetext"),
    ("use", "href"),
    ("use", "requiredExtensions"),
    ("use", "role"),
    ("use", "systemLanguage"),
    ("video", "autoplay"),
    ("video", "controls"),
    ("video", "crossorigin"),
    ("video", "height"),
    ("video", "loading"),
    ("video", "loop"),
    ("video", "muted"),
    ("video", "playsinline"),
    ("video", "poster"),
    ("video", "preload"),
    ("video", "src"),
    ("video", "width"),
    ("view", "aria-activedescendant"),
    ("view", "aria-atomic"),
    ("view", "aria-autocomplete"),
    ("view", "aria-busy"),
    ("view", "aria-checked"),
    ("view", "aria-colcount"),
    ("view", "aria-colindex"),
    ("view", "aria-colspan"),
    ("view", "aria-controls"),
    ("view", "aria-current"),
    ("view", "aria-describedby"),
    ("view", "aria-details"),
    ("view", "aria-disabled"),
    ("view", "aria-dropeffect"),
    ("view", "aria-errormessage"),
    ("view", "aria-expanded"),
    ("view", "aria-flowto"),
    ("view", "aria-grabbed"),
    ("view", "aria-haspopup"),
    ("view", "aria-hidden"),
    ("view", "aria-invalid"),
    ("view", "aria-keyshortcuts"),
    ("view", "aria-label"),
    ("view", "aria-labelledby"),
    ("view", "aria-level"),
    ("view", "aria-live"),
    ("view", "aria-modal"),
    ("view", "aria-multiline"),
    ("view", "aria-multiselectable"),
    ("view", "aria-orientation"),
    ("view", "aria-owns"),
    ("view", "aria-placeholder"),
    ("view", "aria-posinset"),
    ("view", "aria-pressed"),
    ("view", "aria-readonly"),
    ("view", "aria-relevant"),
    ("view", "aria-required"),
    ("view", "aria-roledescription"),
    ("view", "aria-rowcount"),
    ("view", "aria-rowindex"),
    ("view", "aria-rowspan"),
    ("view", "aria-selected"),
    ("view", "aria-setsize"),
    ("view", "aria-sort"),
    ("view", "aria-valuemax"),
    ("view", "aria-valuemin"),
    ("view", "aria-valuenow"),
    ("view", "aria-valuetext"),
    ("view", "preserveAspectRatio"),
    ("view", "role"),
    ("view", "viewBox"),
    ("view", "zoomAndPan"),
];
