#!/bin/sh
# Renders the Homebrew tap's formula for one released version
# (proposal/distribution.md §4):
#
#   scripts/brew-formula.sh 0.14.0 sha256sums.txt > homebrew/Formula/vilan.rb
#
# — where `sha256sums.txt` is the checksum file the release carries beside its
# archives. The formula goes to stdout; nothing here writes to the tap, or
# anywhere else.
#
# This script is the *only* place the formula's text exists. The release
# workflow (.github/workflows/release.yml, job `publish-brew`) runs it against
# the tag's own checksums and commits the result to vilan-lang/homebrew-vilan;
# `homebrew/Formula/vilan.rb` in this repository is the same command's output
# for the current release — the bytes that seeded the tap. Neither is
# hand-edited: crates/vilan-cli/tests/brew_formula.rs re-runs this script and
# compares, so the formula CI pushes and the formula a reviewer reads cannot
# drift apart.
#
# A formula pins a version: every `url` names the `v<version>` tag's download
# path, never `releases/latest`, whose bytes change under a fixed `sha256` and
# would break every install the day after a release.
set -eu

VERSION="${1:?usage: scripts/brew-formula.sh <version> <sha256sums file>}"
SUMS="${2:?usage: scripts/brew-formula.sh <version> <sha256sums file>}"

BASE_URL="https://github.com/vilan-lang/vilan/releases/download/v$VERSION"

fail() { printf 'brew-formula: %s\n' "$1" >&2; exit 1; }

[ -f "$SUMS" ] || fail "no such checksum file: $SUMS"

# The four unix targets of the release matrix
# (.github/workflows/release.yml), each with the Homebrew `on_*` pair that
# selects it. The matrix's fifth target, `x86_64-pc-windows-msvc`, has no row:
# Homebrew does not run on Windows, and `install.ps1` is that platform's
# channel. crates/vilan-cli/tests/brew_formula.rs pins this table against the
# matrix, so a sixth target cannot be added there without being decided here.
TARGETS="aarch64-apple-darwin:macos:arm
x86_64-apple-darwin:macos:intel
aarch64-unknown-linux-musl:linux:arm
x86_64-unknown-linux-musl:linux:intel"

asset_of() { printf 'vilan-%s.tar.gz' "$1"; }

# The checksum recorded for one asset, or the empty string. `sha256sum`'s
# format is `<hash>  <name>`, so the name is the second field — matched whole,
# not by a substring, because the release also carries the archives whose names
# this one is a prefix of.
sha_of() { awk -v want="$1" '$2 == want { print $1; exit }' "$SUMS"; }

# Every target is checked before a single line is emitted, and every failure is
# reported at once: a formula rendered from a checksum file that lost a target
# is not a partial formula, it is one Homebrew refuses to install on the
# platform that went missing.
problems=""
for row in $TARGETS; do
    asset="$(asset_of "${row%%:*}")"
    hash="$(sha_of "$asset")"
    if [ -z "$hash" ]; then
        problems="$problems
  $asset: no entry in $SUMS"
        continue
    fi
    malformed=no
    [ "${#hash}" -eq 64 ] || malformed=yes
    case "$hash" in *[!0-9a-f]*) malformed=yes ;; esac
    if [ "$malformed" = yes ]; then
        problems="$problems
  $asset: $hash is not a sha256"
    fi
done
[ -z "$problems" ] || fail "cannot render the formula:$problems"

# One `on_<os>` block, with the `on_arm` / `on_intel` pair inside it that
# Homebrew selects between. The blocks are what carry `url` and `sha256`; the
# `version` above them is what makes the versionless archive names resolvable
# at all (Homebrew reads a version out of the file name, and ours carries
# none).
platform_block() {
    printf '  on_%s do\n' "$1"
    separator=""
    for row in $TARGETS; do
        target="${row%%:*}"
        rest="${row#*:}"
        [ "${rest%%:*}" = "$1" ] || continue
        printf '%s    on_%s do\n' "$separator" "${rest##*:}"
        printf '      url "%s/%s"\n' "$BASE_URL" "$(asset_of "$target")"
        printf '      sha256 "%s"\n' "$(sha_of "$(asset_of "$target")")"
        printf '    end\n'
        separator="
"
    done
    printf '  end\n'
}

cat << HEADER
# The vilan toolchain — generated by scripts/brew-formula.sh in
# https://github.com/vilan-lang/vilan and pushed here by that repository's
# release workflow. Edit the script, never this file.
class Vilan < Formula
  desc "Language toolchain for vilan: the compiler and the language server"
  homepage "https://vilan-lang.org/docs/"
  version "$VERSION"
  license any_of: ["MIT", "Apache-2.0"]

HEADER
platform_block macos
printf '\n'
platform_block linux
cat << 'FOOTER'

  def install
    bin.install "vilan", "vilan-lsp"
    # Both licenses travel with the binaries they cover: the archive carries
    # them, and redistributing under either one means shipping its text. The
    # third-party notices cover the statically linked crates the same way.
    prefix.install "LICENSE-MIT", "LICENSE-APACHE"
    prefix.install "THIRD-PARTY-NOTICES.txt" if File.exist?("THIRD-PARTY-NOTICES.txt")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/vilan --version")
  end
end
FOOTER
