#!/usr/bin/env python3
"""perf_genapp.py OUTDIR [--seed N] [--views N] [--icons N] [--components N]

The kolt-SHAPED generated application (M105 S4, `performance-gates.md` §5): the public stand-in for the
owner's application in the performance gates, so CI never needs the private repository. Seeded and
deterministic: one seed and one size write byte-identical packages on every machine, and the generator —
not its output — is what the repository carries.

The shape it reproduces is what made v0.42.0's regression invisible to the examples (§5): two entries over
one package (a browser client and a node server), a wire module both reach, a widely imported model file
holding reactive state, a band of view modules written in element syntax with `css { }` blocks, reactive
pipes (`combine(..).map(..)`, `derive`), and one generated icon module the size of an icon set. It extends
E126's view-shaped exhibit (`crates/vilan-lsp/src/keystroke.rs`), whose four recorded counts it shares the
spirit of: nothing is copied from any application — every body is mechanical and every number is
arithmetic on an index or a draw from the seeded generator.

Calibration is the seal's (`perf_gate.py calibrate --kolt DIR`): the generated app's per-phase split
(`VILAN_PHASE_TIMING`) is compared with kolt's, and a phase whose share drifts more than ten points is a
tracker item, not a silent retune. Defaults are the calibrated size."""
import argparse
import os
import random

ICON_CHILDREN = 4


def icon_child(index, child):
    a = (index + child) % 20 + 2
    b = (index + 2 * child) % 18 + 2
    c = (index + 3 * child) % 16 + 1
    d = (index + 5 * child) % 14 + 1
    e = (index + 7 * child) % 12 + 1
    shape = (index + child) % 6
    if shape == 0:
        return f'path d("M{a} {b}h{c}l{d} {e}")'
    if shape == 1:
        return f'path d("M{b} {a}v{c}")'
    if shape == 2:
        return f'circle cx("{a}") cy("{b}") r("{c}")'
    if shape == 3:
        return f'rect x("{a}") y("{b}") width("{c}") height("{d}") rx("{e}")'
    if shape == 4:
        return f'path d("m{a} {b} {c}.{d} {e}")'
    return f'line x1("{a}") y1("{b}") x2("{c}") y2("{d}")'


def icons_module(icons):
    lines = [
        "// GENERATED by scripts/perf_genapp.py: a synthetic icon module, sized like an",
        "// application's icon set. The geometry is arithmetic on the index.",
        "",
        "import std::web::ui::{ View, view };",
        "",
        "export *;",
        "",
        "fun icon_frame(): View {",
        "\t<svg",
        '\t\twidth("24")',
        '\t\theight("24")',
        '\t\tviewBox("0 0 24 24")',
        '\t\tfill("none")',
        '\t\tstroke("currentColor")',
        '\t\tstroke-width("2")',
        "\t/>",
        "}",
        "",
    ]
    for index in range(icons):
        lines.append(f"fun icon_{index:04}(): View {{")
        lines.append("\ticon_frame()")
        for child in range(ICON_CHILDREN):
            lines.append(f"\t\t.child(<{icon_child(index, child)} />)")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


WIRE_MODULE = """// GENERATED by scripts/perf_genapp.py: the wire types both entries reach.
import std::json::Wire;
import std::range::Range;

export *;

[derive(Wire, PartialEq, Debug)]
struct Item {
\tid: i32,
\ttitle: str,
\tdone: bool,
\tweight: i32,
}

[derive(Wire, PartialEq)]
struct Group {
\tid: i32,
\tname: str,
\titems: List<Item>,
}

fun item(id: i32, title: str): Item {
\tItem { id, title, done = false, weight = id % 7 }
}

fun group(id: i32, name: str, size: i32): Group {
\tmut items: List<Item> = [];
\tfor at in Range::new(0, size) {
\t\titems.push(item(id * 100 + at, i"{name} {at}"));
\t}
\tGroup { id, name, items }
}

fun total_weight(group: Group): i32 {
\tmut sum = 0;
\tfor item in group.items {
\t\tsum = sum + item.weight;
\t}
\tsum
}
"""

MODEL_MODULE = """// GENERATED by scripts/perf_genapp.py: the widely imported client model.
import std::reactive::{ Source, combine };
import pkg::wire::{ Group, Item, group };

export *;

struct Model {
\ttitle: SignalCell<str>,
\tselected: SignalCell<i32>,
\tcount: SignalCell<i32>,
\tfilter: SignalCell<str>,
\tgroups: SignalCell<List<Group>>,
}

impl Model {
\tfun new(): Model {
\t\tModel {
\t\t\ttitle = Signal::new("app"),
\t\t\tselected = Signal::new(0),
\t\t\tcount = Signal::new(0),
\t\t\tfilter = Signal::new(""),
\t\t\tgroups = Signal::new([group(1, "inbox", 3), group(2, "later", 2)]),
\t\t}
\t}

\tfun label(self): SignalCell<str> {
\t\tcombine((self.title, self.count)).derive(|(title, count)| i"{title} ({count})").cell()
\t}

\tfun summary(self): SignalCell<str> {
\t\tcombine((self.filter, self.selected)).derive(|(filter, selected)| i"{filter}:{selected}").cell()
\t}

\tfun bump(self) {
\t\tself.count.set(self.count.get() + 1);
\t}

\tfun select(self, id: i32) {
\t\tself.selected.set(id);
\t}
}

fun render_label<S: Source<str>>(source: S): View {
\t<span .child(source.get()) />
}

fun tally<T: Source<i32>>(source: T, offset: i32): i32 {
\tsource.get() + offset
}
"""


def view_module(index, components, icons, rng):
    """One view module: element-syntax components over the model, the icons and a css block."""
    lines = [
        "// GENERATED by scripts/perf_genapp.py: one view module.",
        "import pkg::icons;",
        "import pkg::model::{ Model, render_label, tally };",
        "import pkg::wire::{ Item };",
        "",
        "export *;",
        "",
    ]
    padding = rng.randint(1, 4)
    radius = rng.randint(1, 6)
    lines += [
        "let row_style = css {",
        f"\tpadding(rem({padding}));",
        f"\tgap(rem({radius} / 16));",
        "\twidth(pct(100));",
        "};",
        "",
        "fun chip_mark(selected: bool): str {",
        "\tif selected { \"*\" } else { \"\" }",
        "}",
        "",
        f"fun chip_{index}(label: str, selected: bool): View {{",
        "\t<span .styled(row_style)>",
        "\t\t{label}",
        "\t\t{chip_mark(selected)}",
        "\t</span>",
        "}",
        "",
        f"fun item_row_{index}(item: Item): View {{",
        f"\t<li .child(chip_{index}(item.title, item.done)) .child(i\"{{item.weight}}\") />",
        "}",
        "",
    ]
    for component in range(components):
        icon = rng.randrange(max(icons, 1))
        offset = rng.randint(0, 9)
        selected = "true" if rng.random() < 0.5 else "false"
        lines += [
            f"fun panel_{index}_{component}(model: Model): View {{",
            "\t<div .styled(row_style)>",
            "\t\t<button on:click(|_| { model.bump(); })>",
            f"\t\t\t{{icons::icon_{icon:04}()}}",
            "\t\t</button>",
            "\t\t{render_label(model.label())}",
            f"\t\t{{chip_{index}(\"panel {component}\", {selected})}}",
            f"\t\t<span .child(i\"{{tally(model.count, {offset})}}\") />",
            "\t</div>",
            "}",
            "",
        ]
    lines += [
        f"fun page_{index}(model: Model): View {{",
        "\t<section>",
    ]
    for component in range(components):
        lines.append(f"\t\t{{panel_{index}_{component}(model)}}")
    lines += ["\t</section>", "}", ""]
    return "\n".join(lines)


def client_entry(views):
    lines = ["// GENERATED by scripts/perf_genapp.py: the browser entry.", "import pkg::model::{ Model };"]
    lines += [f"import pkg::view_{index:03};" for index in range(views)]
    lines += ["", "fun main() {", "\tlet model = Model::new();"]
    lines += [f"\tlet page_{index} = view_{index:03}::page_{index}(model);" for index in range(views)]
    children = " ".join(f".child(page_{index})" for index in range(views))
    lines += [f'\tui::mount_root("app", || <main {children} />);', "}", ""]
    return "\n".join(lines)


SERVER_ENTRY = """// GENERATED by scripts/perf_genapp.py: the node entry.
import std::io::print;
import std::range::Range;
import pkg::wire::{ Group, group, total_weight };

fun handle(id: i32): Group {
\tgroup(id, i"group {id}", id % 5 + 1)
}

fun main() {
\tmut sum = 0;
\tfor id in Range::new(1, 40) {
\t\tsum = sum + total_weight(handle(id));
\t}
\tprint(sum);
}
"""

MANIFEST = """# GENERATED by scripts/perf_genapp.py (M105 S4) - seed {seed}, {views} view modules, {icons} icons.
[package]
name = "genapp"
default-entry = "server"
prelude = "std::web::prelude"
generated = "src/icons.vl"

[entry.client]
target = "browser"

[entry.server]
"""


def generate(out, seed=46, views=60, icons=1791, components=6):
    rng = random.Random(seed)
    source = os.path.join(out, "src")
    os.makedirs(source, exist_ok=True)
    files = {
        os.path.join(out, "vilan.toml"): MANIFEST.format(seed=seed, views=views, icons=icons),
        os.path.join(source, "icons.vl"): icons_module(icons),
        os.path.join(source, "wire.vl"): WIRE_MODULE,
        os.path.join(source, "model.vl"): MODEL_MODULE,
        os.path.join(source, "client.vl"): client_entry(views),
        os.path.join(source, "server.vl"): SERVER_ENTRY,
    }
    for index in range(views):
        files[os.path.join(source, f"view_{index:03}.vl")] = view_module(index, components, icons, rng)
    lines = 0
    for path, text in files.items():
        with open(path, "w") as handle:
            handle.write(text)
        lines += text.count("\n")
    return lines


def generate_plain(out, modules):
    """A plain package of `modules` modules of ~150 lines each — structs with derives, a list loop, an
    `Option` match, arithmetic; no views, styles or reactive state — one entry importing all of them.
    `performance-gates.md` §6.2's floor (papers-b-45's `gen_slope.py`, carried here so the growth gate
    needs nothing outside the repository): two sizes give the marginal cost of a thousand lines."""
    source = os.path.join(out, "src")
    os.makedirs(source, exist_ok=True)
    with open(os.path.join(out, "vilan.toml"), "w") as handle:
        handle.write('[package]\nname = "slope"\n\n[entry.main]\n')
    lines_written = 0
    for module in range(modules):
        lines = ["import std::range::Range;", "", "export *;", ""]
        for k in range(6):
            lines += [
                "[derive(PartialEq, Debug)]",
                f"struct Item{module}_{k} {{ id: i32, name: str, weight: i32 }}",
                "",
                f"fun make{module}_{k}(id: i32): Item{module}_{k} {{",
                f'\tItem{module}_{k} {{ id, name = "item", weight = id * {k + 1} }}',
                "}",
                "",
                f"fun pick{module}_{k}(items: List<Item{module}_{k}>, wanted: i32): Option<i32> {{",
                "\tmut found = None;",
                "\tfor item in items {",
                "\t\tif item.id == wanted { found = Some(item.weight); }",
                "\t}",
                "\tfound",
                "}",
                "",
                f"fun score{module}_{k}(n: i32): i32 {{",
                f"\tmut items: List<Item{module}_{k}> = [];",
                f"\tfor i in Range::new(0, n) {{ items.push(make{module}_{k}(i)); }}",
                f"\tmatch pick{module}_{k}(items, n / 2) {{",
                "\t\tSome(let w) => w + 1,",
                "\t\tNone => 0,",
                "\t}",
                "}",
                "",
            ]
        lines += [f"fun total{module}(n: i32): i32 {{",
                  "\t" + " + ".join(f"score{module}_{k}(n)" for k in range(6)), "}", ""]
        text = "\n".join(lines)
        lines_written += text.count("\n")
        with open(os.path.join(source, f"m{module}.vl"), "w") as handle:
            handle.write(text)
    main_lines = [f"import pkg::m{module}::total{module};" for module in range(modules)]
    main_lines += ["", "fun main() {", "\tmut sum = 0;"]
    main_lines += [f"\tsum = sum + total{module}(3);" for module in range(modules)]
    main_lines += ["\tprint(sum);", "}", ""]
    text = "\n".join(main_lines)
    with open(os.path.join(source, "main.vl"), "w") as handle:
        handle.write(text)
    return lines_written + text.count("\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("out")
    parser.add_argument("--seed", type=int, default=46)
    parser.add_argument("--views", type=int, default=60)
    parser.add_argument("--icons", type=int, default=1791)
    parser.add_argument("--components", type=int, default=6)
    parser.add_argument("--plain", type=int, metavar="MODULES",
                        help="write the plain N-module package of the growth gate instead")
    options = parser.parse_args()
    if options.plain:
        lines = generate_plain(options.out, options.plain)
        print(f"wrote {options.out}: {lines} lines ({options.plain} plain modules)")
        return
    lines = generate(options.out, options.seed, options.views, options.icons, options.components)
    print(f"wrote {options.out}: {lines} lines (seed {options.seed}, {options.views} views, {options.icons} icons)")


if __name__ == "__main__":
    main()
