//! The toolchain's embedded `std` — how an installed `vilan` finds its
//! standard library (proposal/releases.md §3).
//!
//! The compiler's std pipeline is filesystem-shaped end to end (layer probing,
//! module listing, `macro_std` beside `std`, manifests), so rather than teach
//! the loader a virtual filesystem, the binary carries the `std` and
//! `macro_std` package trees as data ([`FILES`], generated by `build.rs`) and
//! [`materialize`]s them once into a real directory:
//! `~/.vilan/std-cache/<CONTENT_HASH>/`. The loader then reads ordinary files,
//! and editor go-to-definition into std lands on ordinary files.
//!
//! The cache directory is keyed by [`CONTENT_HASH`], so a rebuilt binary with
//! a different std materializes fresh — the cache can never be stale — and an
//! existing directory is complete by construction: the tree is written to a
//! temporary sibling and atomically renamed into place.

use std::fs;
use std::path::{Path, PathBuf};

include!(concat!(env!("OUT_DIR"), "/embedded_std.rs"));

/// Materializes the embedded toolchain into the default cache
/// (`~/.vilan/std-cache`, or the system temp directory when no home is
/// available) and returns the `std` **package directory** within it — the
/// value `resolve_std` expects. Cheap after the first call: an existing cache
/// entry is returned without touching its contents.
pub fn materialize() -> Result<PathBuf, String> {
    materialize_into(&default_cache_root())
}

/// The default materialization cache root: `~/.vilan/std-cache`, or the system
/// temp directory when no home is available. Shared by [`materialize`] and the
/// upgrade command's cache pruning.
pub fn default_cache_root() -> PathBuf {
    home_dir()
        .map(|home| home.join(".vilan").join("std-cache"))
        .unwrap_or_else(|| std::env::temp_dir().join("vilan-std-cache"))
}

/// Remove cache entries (content-hash trees and crashed `.staging-*`
/// leftovers) whose directory mtime — their creation time; entries are never
/// touched after the atomic rename — is older than `max_age`. Returns how many
/// were removed; a missing root or an unremovable entry is not an error.
///
/// The age guard is the concurrency story: an entry younger than `max_age` may
/// belong to a running binary (std files are read lazily during compilation),
/// so it is left alone. In the rare race — a long-running old binary whose
/// entry ages past the guard while an upgrade prunes — the next resolution
/// simply re-materializes: [`materialize_into`] is idempotent and atomic.
pub fn prune_stale(cache_root: &Path, max_age: std::time::Duration) -> usize {
    let Ok(entries) = std::fs::read_dir(cache_root) else {
        return 0;
    };
    let now = std::time::SystemTime::now();
    let mut removed = 0;
    for entry in entries.flatten() {
        let path = entry.path();
        if !path.is_dir() {
            continue;
        }
        let stale = entry
            .metadata()
            .and_then(|metadata| metadata.modified())
            .ok()
            .and_then(|modified| now.duration_since(modified).ok())
            .is_some_and(|age| age > max_age);
        if stale && std::fs::remove_dir_all(&path).is_ok() {
            removed += 1;
        }
    }
    removed
}

/// [`materialize`] into an explicit cache root (the seam tests use).
pub fn materialize_into(cache_root: &Path) -> Result<PathBuf, String> {
    let target = cache_root.join(CONTENT_HASH);
    let std_dir = target.join("std");
    // Complete by construction: only fully-written trees are renamed in.
    if target.is_dir() {
        return Ok(std_dir);
    }

    // Write the whole tree beside the target, then rename it into place —
    // concurrent first runs race benignly (one rename wins, the loser sees the
    // winner's identical tree).
    let staging = cache_root.join(format!(".staging-{}-{}", CONTENT_HASH, std::process::id()));
    let _ = fs::remove_dir_all(&staging);
    for (key, contents) in FILES {
        let path = staging.join(key);
        let parent = path.parent().expect("every embedded file has a parent");
        fs::create_dir_all(parent)
            .map_err(|error| format!("cannot create {}: {error}", parent.display()))?;
        fs::write(&path, contents)
            .map_err(|error| format!("cannot write {}: {error}", path.display()))?;
    }
    match fs::rename(&staging, &target) {
        Ok(()) => Ok(std_dir),
        Err(error) => {
            let _ = fs::remove_dir_all(&staging);
            if target.is_dir() {
                return Ok(std_dir); // lost the race; the winner's tree is identical
            }
            Err(format!(
                "cannot move the std cache into place at {}: {error}",
                target.display()
            ))
        }
    }
}

/// The user's home directory, from the environment. `std::env::home_dir` is
/// avoided for its Windows history; the plain variables are exactly what the
/// install script and shells define.
///
/// The ORDER is per-platform (`windows-support.md` §5). On Windows
/// `USERPROFILE` is the native variable and is consulted first: Git-Bash/MSYS
/// also set `HOME`, to a `/`-rooted MSYS pseudo-path that Win32 cannot
/// resolve, so preferring it would put the std cache somewhere unusable rather
/// than fall through. Unix keeps `HOME` first, exactly as before. Each
/// candidate is checked for emptiness on its own, so a set-but-empty variable
/// falls through to the next instead of ending the search.
fn home_dir() -> Option<PathBuf> {
    home_dir_from(cfg!(windows), |name| std::env::var_os(name))
}

/// [`home_dir`]'s decision, with the platform and the environment as plain
/// inputs — so both orders are pinnable from either platform without mutating
/// the process environment (which no test may do safely in parallel).
fn home_dir_from(
    windows: bool,
    lookup: impl Fn(&str) -> Option<std::ffi::OsString>,
) -> Option<PathBuf> {
    let variable = |name: &str| {
        lookup(name)
            .filter(|value| !value.is_empty())
            .map(PathBuf::from)
    };
    let order = if windows {
        ["USERPROFILE", "HOME"]
    } else {
        ["HOME", "USERPROFILE"]
    };
    order.into_iter().find_map(variable)
}

#[cfg(test)]
mod tests {
    use super::home_dir_from;
    use std::ffi::OsString;
    use std::path::PathBuf;

    /// A stand-in environment: `(name, value)` pairs, absent names missing.
    fn environment<'pairs>(
        pairs: &'pairs [(&'pairs str, &'pairs str)],
    ) -> impl Fn(&str) -> Option<OsString> + 'pairs {
        move |name| {
            pairs
                .iter()
                .find(|(key, _)| *key == name)
                .map(|(_, value)| OsString::from(*value))
        }
    }

    #[test]
    fn unix_prefers_home() {
        let both = environment(&[("HOME", "/srv/dev"), ("USERPROFILE", "/srv/profile")]);
        assert_eq!(home_dir_from(false, &both), Some(PathBuf::from("/srv/dev")));
    }

    #[test]
    fn windows_prefers_userprofile_over_an_msys_home() {
        // Git-Bash/MSYS sets HOME to a pseudo-path Win32 cannot resolve, so
        // preferring it would pick an unusable cache root
        // (windows-support.md §5).
        let both = environment(&[("HOME", "/msys/dev"), ("USERPROFILE", r"C:\profiles\dev")]);
        assert_eq!(
            home_dir_from(true, &both),
            Some(PathBuf::from(r"C:\profiles\dev"))
        );
    }

    #[test]
    fn each_platform_falls_back_to_the_other_variable() {
        // The install-test shape: HOME seeded, USERPROFILE removed. It must
        // keep working on Windows too, where HOME is now the fallback.
        let home_only = environment(&[("HOME", "/scratch/home")]);
        assert_eq!(
            home_dir_from(true, &home_only),
            Some(PathBuf::from("/scratch/home"))
        );
        let profile_only = environment(&[("USERPROFILE", r"C:\profiles\dev")]);
        assert_eq!(
            home_dir_from(false, &profile_only),
            Some(PathBuf::from(r"C:\profiles\dev"))
        );
    }

    #[test]
    fn a_set_but_empty_variable_falls_through() {
        // Each candidate is tested for emptiness on its own. This CHANGED unix
        // behavior too — the non-empty filter used to sit after the `or_else`,
        // so an empty `HOME` ended the search at `None` instead of falling
        // through — so both platforms' cells are pinned.
        let empty_first = environment(&[("USERPROFILE", ""), ("HOME", "/scratch/home")]);
        assert_eq!(
            home_dir_from(true, &empty_first),
            Some(PathBuf::from("/scratch/home"))
        );
        let empty_home = environment(&[("HOME", ""), ("USERPROFILE", "/srv/profile")]);
        assert_eq!(
            home_dir_from(false, &empty_home),
            Some(PathBuf::from("/srv/profile")),
            "an empty HOME falls through to USERPROFILE on unix as well"
        );
        // Nothing left to fall through to, on either platform.
        assert_eq!(home_dir_from(true, environment(&[("HOME", "")])), None);
        assert_eq!(home_dir_from(false, environment(&[("HOME", "")])), None);
    }

    #[test]
    fn no_home_variable_at_all_is_none() {
        assert_eq!(home_dir_from(false, environment(&[])), None);
        assert_eq!(home_dir_from(true, environment(&[])), None);
    }
}
