//! The toolchain's embedded `std` — how an installed `vilan` finds its
//! standard library (proposal/releases.md §3).
//!
//! The compiler's std pipeline is filesystem-shaped end to end (layer probing,
//! module listing, `macro_std` beside `std`, manifests), so rather than teach
//! the loader a virtual filesystem, the binary carries the `std` and
//! `macro_std` package trees as data ([`FILES`], generated by `build.rs`) and
//! [`materialize`]s them once into a real directory:
//! `~/.vilan/std-cache/<CONTENT_HASH>/`. The loader then reads ordinary files,
//! and editor go-to-definition into std lands on ordinary files.
//!
//! The cache directory is keyed by [`CONTENT_HASH`], so a rebuilt binary with
//! a different std materializes fresh — the cache can never be stale — and an
//! existing directory is complete by construction: the tree is written to a
//! temporary sibling and atomically renamed into place.
//!
//! The same mechanism carries a SECOND tree since tracker F19: `vilan-rt`, the
//! runtime the emit-Rust backend's generated cargo project depends on by path
//! ([`RT_FILES`], [`materialize_rt`], `~/.vilan/rt-cache/<RT_CONTENT_HASH>/`).
//! It lives here rather than in `vilan-rust` because `~/.vilan`'s layout is
//! this crate's — one place to name a cache root, so the CLI and the language
//! server can never disagree about where one is — and it takes its own root and
//! its own hash so the two trees never invalidate each other.

use std::fs;
use std::path::{Path, PathBuf};

include!(concat!(env!("OUT_DIR"), "/embedded_std.rs"));

/// Materializes the embedded toolchain into the default cache
/// (`~/.vilan/std-cache`, or the system temp directory when no home is
/// available) and returns the `std` **package directory** within it — the
/// value `resolve_std` expects. Cheap after the first call: an existing cache
/// entry is returned without touching its contents.
pub fn materialize() -> Result<PathBuf, String> {
    materialize_into(&default_cache_root())
}

/// The default materialization cache root: `~/.vilan/std-cache`, or the system
/// temp directory when no home is available. Shared by [`materialize`] and the
/// upgrade command's cache pruning.
pub fn default_cache_root() -> PathBuf {
    toolchain_cache("std-cache")
}

/// Materializes the embedded `vilan-rt` and returns the runtime crate's
/// **package directory** — the path the emit-Rust backend's generated
/// `Cargo.toml` points its `vilan-rt = { path = … }` at (tracker F19).
///
/// Why this exists: `--backend rust` writes a cargo project that depends on
/// `vilan-rt` by path, and until F19 the only paths it knew were `$VILAN_RT` and
/// this crate's source sibling — so the native backend worked from a checkout
/// and nowhere else. A released binary has neither, and a materialized copy is
/// the same answer the standard library already takes.
pub fn materialize_rt() -> Result<PathBuf, String> {
    materialize_rt_into(&default_rt_cache_root())
}

/// The runtime cache root: `~/.vilan/rt-cache`, beside the std cache and under
/// the same home-directory rules. Its own root and its own content hash, so a
/// std edit never re-materializes the runtime and a runtime edit never
/// invalidates a machine's std trees.
pub fn default_rt_cache_root() -> PathBuf {
    toolchain_cache("rt-cache")
}

/// [`materialize_rt`] into an explicit cache root (the seam tests use).
pub fn materialize_rt_into(cache_root: &Path) -> Result<PathBuf, String> {
    let target = cache_root.join(RT_CONTENT_HASH);
    let crate_dir = target.join("vilan-rt");
    if target.is_dir() {
        return Ok(crate_dir);
    }
    let staging = cache_root.join(format!(
        ".staging-{}-{}",
        RT_CONTENT_HASH,
        std::process::id()
    ));
    let _ = fs::remove_dir_all(&staging);
    let mut written: Vec<(PathBuf, &str)> = RT_FILES
        .iter()
        .map(|(key, contents)| (staging.join(key), *contents))
        .collect();
    written.push((staging.join("vilan-rt").join("Cargo.toml"), RT_MANIFEST));
    // F18 slice 2: the SQLite crate materializes beside the runtime, under the
    // same hash, because the generated cargo manifest reaches it as a sibling
    // of the runtime path.
    written.push((
        staging.join("vilan-rt-sqlite").join("Cargo.toml"),
        RT_SQLITE_MANIFEST,
    ));
    for (path, contents) in written {
        let parent = path.parent().expect("every embedded file has a parent");
        fs::create_dir_all(parent)
            .map_err(|error| format!("cannot create {}: {error}", parent.display()))?;
        fs::write(&path, contents)
            .map_err(|error| format!("cannot write {}: {error}", path.display()))?;
    }
    match fs::rename(&staging, &target) {
        Ok(()) => {
            prune_stale(cache_root, STALE_AFTER);
            Ok(crate_dir)
        }
        Err(error) => {
            let _ = fs::remove_dir_all(&staging);
            if target.is_dir() {
                return Ok(crate_dir); // lost the race; the winner's tree is identical
            }
            Err(format!(
                "cannot move the runtime cache into place at {}: {error}",
                target.display()
            ))
        }
    }
}

/// Where a READ-ONLY command's on-disk memory lives: `~/.vilan/check-cache`,
/// beside the std cache and under the same home-directory rules (tracker N92).
///
/// `dist/.cache` is the BUILD's (N63, ruled 2026-09-07), and the argument for
/// it is `rm -rf dist` — one gesture that means "recompile everything, macro
/// worlds included". `vilan check` emits no artifacts at all, so it has no
/// `dist/` of its own to keep memory in: writing one created a build directory
/// in a tree nobody asked to build, and made a command that reads a package
/// MUTATE it. (`split.rs`'s fixture loader read every entry of its directory
/// and failed ten tests with `IsADirectory` when one was left behind, which is
/// how the cost of that showed up.)
///
/// So a check's table is keyed by the package's canonical path under this root
/// instead. The objection N63 raised to a machine-global cache — a stale one is
/// unreachable to `rm -rf` — is answered by `vilan cache prune`, which sweeps
/// this root beside the std trees, and by the table's own header, which carries
/// the toolchain version and a hash of `macro_std` and discards the whole file
/// when either moves.
pub fn default_check_cache_root() -> PathBuf {
    toolchain_cache("check-cache")
}

/// Where **git dependencies** are cached: `~/.vilan/git-deps`, beside the std
/// cache and under the same home-directory rules (`home_dir`, below). The
/// toolchain's `~/.vilan` layout lives in one crate so the CLI and the language
/// server can never disagree about where a cache is — the fetching and the
/// pruning of that tree are `vilan_core::git_dep`'s (its entries are keyed by
/// content, so unlike a std tree they are never stale and are not age-pruned).
pub fn default_git_dep_root() -> PathBuf {
    toolchain_cache("git-deps")
}

/// One `~/.vilan/<leaf>` cache root, falling back to a temp directory (named
/// `vilan-<leaf>`) when the environment names no home.
fn toolchain_cache(leaf: &str) -> PathBuf {
    home_dir()
        .map(|home| home.join(".vilan").join(leaf))
        .unwrap_or_else(|| std::env::temp_dir().join(format!("vilan-{leaf}")))
}

/// How old a cache entry must be before anything will remove it: one week.
///
/// One constant, three consumers — [`materialize_into`]'s prune, `vilan
/// upgrade`'s housekeeping, and `vilan cache prune`'s default — because they
/// are one policy and a second spelling of it would be a second policy.
pub const STALE_AFTER: std::time::Duration = std::time::Duration::from_secs(7 * 24 * 60 * 60);

/// One entry of the std cache: a content-hash tree, or a crashed `.staging-*`
/// leftover.
#[derive(Debug, Clone)]
pub struct CacheEntry {
    /// The directory name — a content hash, or `.staging-<hash>-<pid>`.
    pub name: String,
    pub path: PathBuf,
    /// Bytes on disk, summed over the tree.
    pub bytes: u64,
    /// How long ago the entry was created, from its directory mtime — `None`
    /// when the platform will not answer (the entry is then treated as young).
    pub age: Option<std::time::Duration>,
    /// Whether this is a tree THIS binary materializes into. It is never
    /// removed: the next resolution would write it straight back, and a
    /// concurrent compile is reading it right now.
    ///
    /// EITHER hash answers, because one walk serves both roots (the std trees
    /// and, since F19, the runtime trees) and a root only ever holds its own
    /// kind. A cross-match would take a 64-bit collision between the two
    /// tables, and its whole effect would be sparing one extra tree — the
    /// conservative direction, which is the direction this flag exists for.
    pub current: bool,
}

/// Every entry under `cache_root`, in `read_dir` order. A missing or unreadable
/// root is an empty list, not an error.
pub fn cache_entries(cache_root: &Path) -> Vec<CacheEntry> {
    let Ok(entries) = std::fs::read_dir(cache_root) else {
        return Vec::new();
    };
    let now = std::time::SystemTime::now();
    let mut out = Vec::new();
    for entry in entries.flatten() {
        let path = entry.path();
        if !path.is_dir() {
            continue;
        }
        let name = entry.file_name().to_string_lossy().into_owned();
        let age = entry
            .metadata()
            .and_then(|metadata| metadata.modified())
            .ok()
            .and_then(|modified| now.duration_since(modified).ok());
        out.push(CacheEntry {
            current: name == CONTENT_HASH || name == RT_CONTENT_HASH,
            bytes: directory_bytes(&path),
            name,
            path,
            age,
        });
    }
    out
}

/// Bytes under `directory`, summed over every file it holds. An unreadable
/// entry contributes nothing rather than failing the walk: this number is
/// reported to a human, never depended on.
fn directory_bytes(directory: &Path) -> u64 {
    let Ok(entries) = std::fs::read_dir(directory) else {
        return 0;
    };
    let mut total = 0;
    for entry in entries.flatten() {
        match entry.file_type() {
            Ok(kind) if kind.is_dir() => total += directory_bytes(&entry.path()),
            Ok(_) => total += entry.metadata().map(|metadata| metadata.len()).unwrap_or(0),
            Err(_) => {}
        }
    }
    total
}

/// Remove cache entries (content-hash trees and crashed `.staging-*`
/// leftovers) whose directory mtime — their creation time; entries are never
/// touched after the atomic rename — is older than `max_age`, or EVERY entry
/// when `max_age` is `None`. Returns the entries removed, in `read_dir` order;
/// `dry_run` returns exactly the same list and removes nothing. A missing root
/// or an unremovable entry is not an error.
///
/// The age guard is the concurrency story: an entry younger than `max_age` may
/// belong to a running binary (std files are read lazily during compilation),
/// so it is left alone. In the rare race — a long-running old binary whose
/// entry ages past the guard while an upgrade prunes — the next resolution
/// simply re-materializes: [`materialize_into`] is idempotent and atomic.
///
/// THIS binary's own entry ([`CONTENT_HASH`]) is never removed, at any age and
/// under `None` alike. Removing it would delete a tree the running compile is
/// reading and buy nothing: the next resolution writes it straight back.
pub fn prune(
    cache_root: &Path,
    max_age: Option<std::time::Duration>,
    dry_run: bool,
) -> Vec<CacheEntry> {
    let mut removed = Vec::new();
    for entry in cache_entries(cache_root) {
        if entry.current {
            continue;
        }
        let stale = match max_age {
            None => true,
            Some(max_age) => entry.age.is_some_and(|age| age > max_age),
        };
        if !stale {
            continue;
        }
        if dry_run || std::fs::remove_dir_all(&entry.path).is_ok() {
            removed.push(entry);
        }
    }
    removed
}

/// [`prune`] by age, counted — the shape `vilan upgrade` has always called.
pub fn prune_stale(cache_root: &Path, max_age: std::time::Duration) -> usize {
    prune(cache_root, Some(max_age), false).len()
}

/// [`materialize`] into an explicit cache root (the seam tests use).
pub fn materialize_into(cache_root: &Path) -> Result<PathBuf, String> {
    let target = cache_root.join(CONTENT_HASH);
    let std_dir = target.join("std");
    // Complete by construction: only fully-written trees are renamed in.
    if target.is_dir() {
        return Ok(std_dir);
    }

    // Write the whole tree beside the target, then rename it into place —
    // concurrent first runs race benignly (one rename wins, the loser sees the
    // winner's identical tree).
    let staging = cache_root.join(format!(".staging-{}-{}", CONTENT_HASH, std::process::id()));
    let _ = fs::remove_dir_all(&staging);
    for (key, contents) in FILES {
        let path = staging.join(key);
        let parent = path.parent().expect("every embedded file has a parent");
        fs::create_dir_all(parent)
            .map_err(|error| format!("cannot create {}: {error}", parent.display()))?;
        fs::write(&path, contents)
            .map_err(|error| format!("cannot write {}: {error}", path.display()))?;
    }
    match fs::rename(&staging, &target) {
        Ok(()) => {
            // L21: the moment a NEW hash lands is the only moment the cache
            // GROWS, so it is the moment to drop what no binary can use.
            // Before this, `vilan upgrade` was the sole pruner — and a
            // toolchain refreshed from source never runs it, so every lane
            // binary and every release build left a tree behind forever (374
            // entries, 316 MB on the owner's machine in two months).
            //
            // Safe by construction, and the guard does the work: an entry's
            // mtime is its creation time and nothing touches it after the
            // rename, so the tree written a moment ago is the youngest thing
            // in the root and survives its own prune — as does every entry a
            // binary started this week might still be reading. The race a week
            // opens is the one `upgrade` has always accepted, and its cost is
            // a re-materialization.
            prune_stale(cache_root, STALE_AFTER);
            Ok(std_dir)
        }
        Err(error) => {
            let _ = fs::remove_dir_all(&staging);
            if target.is_dir() {
                return Ok(std_dir); // lost the race; the winner's tree is identical
            }
            Err(format!(
                "cannot move the std cache into place at {}: {error}",
                target.display()
            ))
        }
    }
}

/// The user's home directory, from the environment. `std::env::home_dir` is
/// avoided for its Windows history; the plain variables are exactly what the
/// install script and shells define.
///
/// The ORDER is per-platform (`windows-support.md` §5). On Windows
/// `USERPROFILE` is the native variable and is consulted first: Git-Bash/MSYS
/// also set `HOME`, to a `/`-rooted MSYS pseudo-path that Win32 cannot
/// resolve, so preferring it would put the std cache somewhere unusable rather
/// than fall through. Unix keeps `HOME` first, exactly as before. Each
/// candidate is checked for emptiness on its own, so a set-but-empty variable
/// falls through to the next instead of ending the search.
fn home_dir() -> Option<PathBuf> {
    home_dir_from(cfg!(windows), |name| std::env::var_os(name))
}

/// [`home_dir`]'s decision, with the platform and the environment as plain
/// inputs — so both orders are pinnable from either platform without mutating
/// the process environment (which no test may do safely in parallel).
fn home_dir_from(
    windows: bool,
    lookup: impl Fn(&str) -> Option<std::ffi::OsString>,
) -> Option<PathBuf> {
    let variable = |name: &str| {
        lookup(name)
            .filter(|value| !value.is_empty())
            .map(PathBuf::from)
    };
    let order = if windows {
        ["USERPROFILE", "HOME"]
    } else {
        ["HOME", "USERPROFILE"]
    };
    order.into_iter().find_map(variable)
}

#[cfg(test)]
mod tests {
    use super::home_dir_from;
    use std::ffi::OsString;
    use std::path::PathBuf;

    /// A stand-in environment: `(name, value)` pairs, absent names missing.
    fn environment<'pairs>(
        pairs: &'pairs [(&'pairs str, &'pairs str)],
    ) -> impl Fn(&str) -> Option<OsString> + 'pairs {
        move |name| {
            pairs
                .iter()
                .find(|(key, _)| *key == name)
                .map(|(_, value)| OsString::from(*value))
        }
    }

    #[test]
    fn unix_prefers_home() {
        let both = environment(&[("HOME", "/srv/dev"), ("USERPROFILE", "/srv/profile")]);
        assert_eq!(home_dir_from(false, &both), Some(PathBuf::from("/srv/dev")));
    }

    #[test]
    fn windows_prefers_userprofile_over_an_msys_home() {
        // Git-Bash/MSYS sets HOME to a pseudo-path Win32 cannot resolve, so
        // preferring it would pick an unusable cache root
        // (windows-support.md §5).
        let both = environment(&[("HOME", "/msys/dev"), ("USERPROFILE", r"C:\profiles\dev")]);
        assert_eq!(
            home_dir_from(true, &both),
            Some(PathBuf::from(r"C:\profiles\dev"))
        );
    }

    #[test]
    fn each_platform_falls_back_to_the_other_variable() {
        // The install-test shape: HOME seeded, USERPROFILE removed. It must
        // keep working on Windows too, where HOME is now the fallback.
        let home_only = environment(&[("HOME", "/scratch/home")]);
        assert_eq!(
            home_dir_from(true, &home_only),
            Some(PathBuf::from("/scratch/home"))
        );
        let profile_only = environment(&[("USERPROFILE", r"C:\profiles\dev")]);
        assert_eq!(
            home_dir_from(false, &profile_only),
            Some(PathBuf::from(r"C:\profiles\dev"))
        );
    }

    #[test]
    fn a_set_but_empty_variable_falls_through() {
        // Each candidate is tested for emptiness on its own. This CHANGED unix
        // behavior too — the non-empty filter used to sit after the `or_else`,
        // so an empty `HOME` ended the search at `None` instead of falling
        // through — so both platforms' cells are pinned.
        let empty_first = environment(&[("USERPROFILE", ""), ("HOME", "/scratch/home")]);
        assert_eq!(
            home_dir_from(true, &empty_first),
            Some(PathBuf::from("/scratch/home"))
        );
        let empty_home = environment(&[("HOME", ""), ("USERPROFILE", "/srv/profile")]);
        assert_eq!(
            home_dir_from(false, &empty_home),
            Some(PathBuf::from("/srv/profile")),
            "an empty HOME falls through to USERPROFILE on unix as well"
        );
        // Nothing left to fall through to, on either platform.
        assert_eq!(home_dir_from(true, environment(&[("HOME", "")])), None);
        assert_eq!(home_dir_from(false, environment(&[("HOME", "")])), None);
    }

    #[test]
    fn no_home_variable_at_all_is_none() {
        assert_eq!(home_dir_from(false, environment(&[])), None);
        assert_eq!(home_dir_from(true, environment(&[])), None);
    }
}
